### ISSUE TITLE
SQL 的最佳实践？

### ISSUE THREAD

**Issue by hedan806** [bilibili/kratos#101]
在使用``SQL``模块时，都是接收原生的``SQL``语句，在这种情况下，如何更好的维护``SQL``语句？或者说会支持和如何使用类似``动态 SQL``的方式吗？

**Comment by realityone** [comment]
目前 80% 常规在线业务逻辑里是不需要动态 SQL 的，使用动态 SQL 时一般伴随多条件的过滤查询，这种查询往往出现在后台业务中。

后台业务中可以考虑使用之后的 sqlbuilder 来辅助构建 SQL。
