### ISSUE TITLE
rpc HelloWorld

### ISSUE THREAD

**Issue by shippomx** [bilibili/kratos#103]
kratos/pkg/net/rpc/warden/internal/benchmark/helloworld/client/greeter_client.go
代码无法运行
	client := warden.NewClient(ccf) // 运行到此处，程序就不能用了。

环境: macos 10.14.4
go version go1.12.4 darwin/amd64
IDE: goland

**Comment by ctrysbita** [comment]
Discovery上了么，目前是依赖discovery服务发现的，未来会抽离 #100

**Comment by shippomx** [comment]
启动按着discovery的示例启动命令启动，没有做其它的配置

**Comment by shippomx** [comment]
client也是通过直连方式连接的server，应该是用不着discovery的

**Comment by ctrysbita** [comment]
理论上应该这样，但是目前还是依赖的，一NewClient就会去连discovery，连不上就崩了。

**Comment by shippomx** [comment]
注释掉 discovery.New()的一部分代码后暂时先让程序跑起来了
