### ISSUE TITLE
kratos 有命令 command  应用入口吗?

### ISSUE THREAD

**Issue by wujunze** [bilibili/kratos#107]
你好:  
       kratos 有命令 command  应用入口吗?    例如每天0点执行一个 command  给用户发邮件提醒

**Comment by tonyboxes** [comment]
是不是类似cron跑某个时间的task？

**Comment by wujunze** [comment]
> 是不是类似cron跑某个时间的task？

对的   类似于 执行一个 command    可以调用框架里面的 Service

**Comment by Terry-Mao** [comment]
crontab类似的第三方github 应该比较多了，所以没有开发，那么为什么不加入基础库呢？

因为单个进程的cron，第三方库很多支持，并且自己利用timer ticket 很容易实现。

但是cron在单机风险是非常大的，我建议可以阅读下Google SRE里提的Google Cron的维护，类似的可以调研一下k8s cronjob ，应该不要局限于单个进程的任务cron执行。
