### ISSUE TITLE
kratos tool: Roadmap

### ISSUE THREAD

**Issue by Terry-Mao** [bilibili/kratos#110]
# 背景

kratos 作为 go-common 最重要的脚手架工具，未来的文档化、功能特点、使用规范对每一个开发都很重要，因此对kratos tool 提出一个整体的畅想。

# 规划

我们把kratos作为一个”壳“来驱动app/tool/ 下所有的小工具集合，这样既收敛使用方式，同时也方便统一维护和升级，从功能来讲我们分为：

- Kratos（包含build、test等）

- HTTP（Blademaster框架）

- gRPC（Warden框架）

- Cache

- Other
因此核心使用方式上，我们参考了go toolchain，使用模型统一为：

```shell
# 方便kratos在shell中使用，我们会建议建议把工具集合统一维护到GOBIN环境变量中，方便后续升级
$ export PATH=PATH:$GOBIN

# 编译，内部驱动bazel来编译
$ kratos build

# 升级
$ kratos upgrade

# 工具链，例如：驱动bmgen工具来生成kratos 项目
$ kratos tool bmgen
```
# 归属

kratos下的每个子工具分散给工具提供者作为OWNER来维护，交由kratos来挂载统一维护index.json（维护版本和提示信息等）

**Comment by wujunze** [comment]
支持 kratos test 命令吗

**Comment by Terry-Mao** [comment]
kratos test还在考虑，还是想直接go test比较方便，最近会加入一个库利用本地docker 解决mock 组件的问题，比如memcache

**Comment by wujunze** [comment]
你好 毛老师 
  我试过 直接执行  go test   会有问题 db 资源没有初始化

**Comment by Terry-Mao** [comment]
还没提pr呢。。。@wujunze

**Comment by wujunze** [comment]
哈哈哈   
     毛老师  你们现在项目的 单元测试是怎么运行  怎么解决的 @Terry-Mao

**Comment by otokaze** [comment]
@wujunze 为此我们开源了：

**Comment by Terry-Mao** [comment]
@wujunze 参考我们的testing/lich package

**Comment by wujunze** [comment]
> @wujunze 参考我们的testing/lich package

OK Thanks
