### ISSUE TITLE
CPU信息不应该从/sys/fs/cgroup/获取

### ISSUE THREAD

**Issue by LoneGunman001** [bilibili/kratos#115]
在Ubuntu on Windows以及类似的系统里，/sys/fs/cgroup/中的信息是不全的。kratos/pkg/stat/sys/cpu中的CPU信息是否可以改为从/proc/cpuinfo中获取？

**Comment by Terry-Mao** [comment]
确实目前不是跨平台兼容的，从/proc/cpuinfo ，存在不兼容docker。 @longXboy 看下跨平台处理下cpu_drawin.go 类似处理？
