### ISSUE TITLE
为什么BM去掉了parth params

### ISSUE THREAD

**Issue by storv** [bilibili/kratos#116]
我看到gin是存在一个解析path中的`xxxx/:BBB` `BBB`这个参数，但是BM中却取消了这个设计、有具体的原因么

**Comment by ctrysbita** [comment]
大概推荐使用Json RPC的标准而不是RESTful？这样的话对proto生成bm比较友好

**Comment by lintanghui** [comment]
一个原因是为了防止prom监控内存暴涨。。

**Comment by Terry-Mao** [comment]
当时主要是为了控制普罗米修斯上报导致的OOM，后续会考虑优化
