### ISSUE TITLE
bm是否支持StaticFS，以及context是否支持cookie的读取和设置？

### ISSUE THREAD

**Issue by dyldea** [bilibili/kratos#117]
gin框架支持静态文件，bm中好像没有？是不是只能做纯API了
另外gin的context中有cookie的读取和设置方法，bm中好像也没有，是不是要自己用原生http实现

**Comment by Terry-Mao** [comment]
我是非常反馈Gin 什么东西都要包一个方法的。
所以我们内部基于Gin改造的时候，阉割了他大部分方法，使用c.Request 对下，可以直接拿到net/http.Request，基于这个来设置Cookie。

另外不打算支持静态文件，因为就是一个微服务网关，不是前端WEB框架
