### ISSUE TITLE
kratos 什么时候 release 一个版本？

### ISSUE THREAD

**Issue by sandacn** [bilibili/kratos#119]
现在在用，发现更新挺多，但是怕过段时间，原来写的项目就跑不起来了，不敢更新 kratos 的版本。 我看很多 github 的库都会 release 固定的版本，这样对改变我们会有预期，而不是现在，一直都是在最新的版本，总担心有一天会爆。不知道 owner 是什么想法？ 可以分享一下吗？

**Comment by Terry-Mao** [comment]
这个因为我们还有大概几十个issue还没修复，修复完毕就会正式打tag，另外我们所有改动都是向下兼容的，因为毕竟是内部搬移够来的，这个可以绝对放心，等我们消灭完这一波issue就会正式release第一个版本，对目前使用没有任何影响

**Comment by sandacn** [comment]
收到，谢谢
