### ISSUE TITLE
go get -u github.com/bilibili/kratos/tool/kratos error

### ISSUE THREAD

**Issue by zanjs** [bilibili/kratos#12]
\github.com\bilibili\kratos\tool\kratos\build.go:16:12: undefined: pty.Start

**Comment by pleasecallmemaoxian** [comment]
同样有这问题

**Comment by yinjk** [comment]
执行`go get -u github.com/bilibili/kratos/tool/kratos`，同出现这个问题：
```shell
# github.com/bilibili/kratos/tool/kratos
tool\kratos\build.go:16:12: undefined: pty.Start
```

**Comment by nicolaslh** [comment]
不能在windows上编译

**Comment by whtiehack** [comment]
不支持windows。

**Comment by zanjs** [comment]
go 大法是 夸平台， 为什么不支持 windows

**Comment by pleasecallmemaoxian** [comment]
> go 大法是 夸平台， 为什么不支持 windows

貌似是这东西调用了Unix下的一些终端命令

**Comment by whtiehack** [comment]
原因是用了 pty 这个库。这个库是不跨平台的。 源码文件 第一行是  `// +build:!windows`
B站的大佬们出来解决一下呀

**Comment by felixhao** [comment]
我们解决下~~（大家都换mac吧😁

**Comment by wuleying** [comment]
$ go get -u github.com/bilibili/kratos/tool/kratos
# cd /Users/luoliang/projects/go/src/github.com/fatih/color; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/fatih/color: exit status 1

**Comment by Terry-Mao** [comment]
@longXboy 这个看下

**Comment by whtiehack** [comment]
@felixhao  合并下呀！~

**Comment by felixhao** [comment]
已修复
