### ISSUE TITLE
改进 warden 日志

### ISSUE THREAD

**Issue by ctrysbita** [bilibili/kratos#120]
目前 warden 默认给客户端与服务端都加上了日志输出的拦截器，但日志输出键值对乱序且无法进行格式化，其中包含的参数容易将敏感信息记录进日志中。

改进方向：
- 日志格式化
- 自定义输出内容

**Comment by Terry-Mao** [comment]
这块代码上有什么建议吗，通过何种方式来初始化内部默认的Logger模块

**Comment by ctrysbita** [comment]
可以在创建服务端/客户端的时候传入option里定义？包括是否启用以及详细的输出格式（类似目前的logger模块）。以及输出项顺序最好可以固定一下（可以在输出格式内定义顺序）

**Comment by Terry-Mao** [comment]
这个可以，我们目前有一个内部mr，同步过来，支持控制参数，client 是可以的，server 会比较麻烦

**Comment by Terry-Mao** [comment]
server 要初始化的时候控制了，而且不能接口级别控制，要么全部生效

**Comment by lcg635** [comment]
希望能增加一个配置, 在打印日志时, 只显示短的文件路径(比如最后面两层目录), 而不是完整的路径. 
@Terry-Mao

**Comment by ctrysbita** [comment]
@lcg635 这个可以通过配置全局日志模块的format实现
