### ISSUE TITLE
没有配置discovery导致程序卡住

### ISSUE THREAD

**Issue by cocktail18** [bilibili/kratos#125]
log 由于默认没有 handler，当discovery 连不上或者 poll 失败，没有打印出报错信息，程序会卡住，建议 文档上补充说明下

解决方案：
初始化一个handler
`log.Init(nil)`

**Comment by sandacn** [comment]
Duplicate of #122 

我这周优化一下这块，你到时候也可以试试

**Comment by Terry-Mao** [comment]
fix
