### ISSUE TITLE
请问什么时间正式发布 1.0 稳定版本

### ISSUE THREAD

**Issue by wujunze** [bilibili/kratos#132]
1. kratos 工程化做的很不错   对微服务支持的不错   脚手架工具不错   
2. 准备在**生产环境项目**使用 
3. new 了一个 demo 在试用   发现有不少 bug  
4. 相关文档  和  一个 完整示例的 demo 项目   官方未来会提供吗  (建议可以发动社区的力量来完善) 
5. 有未来的开发计划 和 RoadMap 吗
6. 感谢开源出来的 kratos 项目

**Comment by lintanghui** [comment]
参见 #119

**Comment by Terry-Mao** [comment]
3、主要是哪些bug，能反馈吗？
4、这个如果可以的话，贡献PR吧
5、Roadmap未来会做出来，不出意外下周就会列一下进来
