### ISSUE TITLE
想问一下文档方面什么时候可以完善

### ISSUE THREAD

**Issue by github-yxb** [bilibili/kratos#143]
最近在做技术选型，觉的kratos挺适合我们的业务。    
但觉的文档方面还比较粗燥，例如服务发现文档没有描述如何检测服务健康状态，希望文档能更完整一些。     
还有有没有出release版本的计划呢？

**Comment by Terry-Mao** [comment]
目前正在tag v 0.1 ，健康监测是blademaster HTTP 框架里面的/monitor/ping 接口，确实需要继续强化文档

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/summary.md

**Comment by tonyboxes** [comment]
文档已经补全，多帮忙看看提些建议~
