### ISSUE TITLE
[Question] warden-quickstart.md中，d.demoClient用的clientconn会得到更新吗

### ISSUE THREAD

**Issue by wangping886** [bilibili/kratos#144]
我的理解通过demoapi.NewClient(cfg)注入到dao中，d.demoClient.SayHello(c, req) 方法请求rpc服务的时候 ，当server端的服务不可用或者新注册了服务地址，d.demoClient用的clientconn会得到更新吗。

**Comment by tonyboxes** [comment]
client conn会通过resolver取到连接，有对应的zone、subset和负载均衡实现

**Comment by wangping886** [comment]
> client conn会通过resolver取到连接，有对应的zone、subset和负载均衡实现
