### ISSUE TITLE
关于引入DI的思考

### ISSUE THREAD

**Issue by CoderPoet** [bilibili/kratos#149]
框架层DI：

遵循面向接口编程的规范，框架应该尽可能对外暴露的是接口，而非具体实现

例如，kratos包装的grpc服务，可以抽离出通用接口，外部可以自行实现接口替换具体使用的实例，比如替换注册中心的实现之类的

-----

业务层DI：

微服务化的项目，可能会把所有方法挂载在一个结构体下，共享结构体里的一些基础服务（比如 service的所有方法都挂载在service结构体下面，共享redis，db，cache等）

这样会有几个问题：
1、服务比较轻量，问题不大，如果服务膨胀，一个类几百个方法，感觉有点不优雅了，当然这个时候可能需要考虑拆分你的服务了。
2、直接依赖具体实现类（例如service结构体里直接引用*dao.Dao），后面如果修改这些依赖的底层实现，可能会带来破坏性更新
3、也不方便直接生成mock代码

依赖可以从具体实现类改成interface 

例如：目前service依赖的 *dao.Dao，其实可以考虑抽象出interface，比如说，抽象出CRUD这些方法组成的interface，service只关心这些方法是否实现了，而不关心具体使用哪一个类。

同理 dao层也是如此。

然后引入wire来自动生成依赖注入的代码，例如：

```

// wire.go
func InitializeApplication(config config.Config) (application, error) {
	wire.Build(
		configSet,
		daoSet,
		serviceSet,
		serverSet,
		newApplication,
	)
	return application{}, nil
}

// inject_service.go

var serviceSet = wire.NewSet(
	user.New,

	provideSession,
)

//  声明 UserService接口，及其依赖，在inject_service编写具体的依赖Provider



```

**Comment by realityone** [comment]
对于 gRPC 而言，proto 生成的代码里就会有 Client 的 interface，理论上使用者可以自己通过各种 mock 工具生成 mock 代码。

对于 Service 本身实现而言，在绝大部分线上微服务的业务逻辑里，在足够简单的时候没必要一定依赖 interface，实际上绝大部分业务逻辑内部的 interface 一辈子也只会有一个实现。

对于复杂业务而言，Service 内部如何组织业务代码实际上是松散的，包括 gRPC 也没有限制你一定要把代码写成某种模式。在业务逻辑复杂的时候你可以自己组织各类 interface。但我的实际感受是很多时候你甚至只需要一个闭包，而不是 interface。

**Comment by Terry-Mao** [comment]
目前kratos tool 生成的代码，Dao 缺失没interface，这个还是要支持的，方便service mock 掉dao来直接实现unit test，对于service 本身的interface，因为gRPC proto已经定义好了，实际上不需要二次定义了，如 @realityone 所说可以直接mock。

我个人意见是：

1. Dao的抽象是需要的；

2. Service依托gRPC的API定义，无需额外定义了

3. 指定DI，大部分情况确实只有一种实现，对于开源项目的通用性和不同服务化程度和粒度，我可能会考虑引入，但不是默认或者强制的。

**Comment by Terry-Mao** [comment]
已经完成Dao的依赖抽象，service 可以直接mock dao来写ut，至于api.proto 会自动生成关于service的interface，api非常方便mock service。

关于google/wire 我单独一个issue
