### ISSUE TITLE
无法找到相应想依赖包

### ISSUE THREAD

**Issue by token01** [bilibili/kratos#15]
go build main.go
main.go:11:2: cannot find package "kratos-demo/internal/server/grpc" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/server/grpc (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/server/grpc (from $GOPATH)
main.go:12:2: cannot find package "kratos-demo/internal/server/http" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/server/http (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/server/http (from $GOPATH)
main.go:13:2: cannot find package "kratos-demo/internal/service" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/service (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/service (from $GOPATH)

**Comment by felixhao** [comment]
直接`go build`呢

**Comment by token01** [comment]
错误一样

go build
main.go:11:2: cannot find package "kratos-demo/internal/server/grpc" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/server/grpc (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/server/grpc (from $GOPATH)
main.go:12:2: cannot find package "kratos-demo/internal/server/http" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/server/http (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/server/http (from $GOPATH)
main.go:13:2: cannot find package "kratos-demo/internal/service" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/kratos-demo/internal/service (from $GOROOT)
	/Users/sunzhenya/Work/go/src/kratos-demo/internal/service (from $GOPATH)

**Comment by felixhao** [comment]
`go env`输出看下环境信息

**Comment by token01** [comment]
go env
GOARCH="amd64"
GOBIN="/Users/sunzhenya/Work/go/bin"
GOCACHE="/Users/sunzhenya/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/sunzhenya/Work/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.4/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1r/jmd5w4j50092jhbwmzgh2x_w0000gn/T/go-build350331133=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by tonyboxes** [comment]
go version是大于1.11不的；
go mod管理依赖，不用clone到gopath目录下面；

我准备把golang.org的依赖，也在go.mod配置replace成github地址的。

**Comment by token01** [comment]
所以问题 是我这边配置的问题？还是版本太高导致的？

**Comment by Terry-Mao** [comment]
你现在 go build 试试，go version 贴出来，刚才解决了go.mod 的部分仓库被墙的问题

**Comment by felixhao** [comment]
@token01 `echo $GO111MODULE`看起来像是没开启go mod，执行这个看下环境变量是否设置为 `on`？

**Comment by token01** [comment]
我试试先  感觉有好多问题 可以帮你们更新

**Comment by tonyboxes** [comment]
跟今天群里那个有点类似，cat go.mod 看看名称是不是 module kratos-demo

**Comment by token01** [comment]
go build main.go  

go: extracting github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/golang/sys v0.0.0-20180905080454-ebe1bf3edb33
go: extracting github.com/BurntSushi/toml v0.3.1
go: extracting github.com/golang/sys v0.0.0-20180905080454-ebe1bf3edb33
go: extracting github.com/golang/protobuf v1.2.0

build command-line-arguments: cannot load kratos/internal/server/grpc: cannot find module providing package kratos/internal/server/grpc

**Comment by token01** [comment]
@felixhao 
 sunzhenya at localhost in ~/Work/go/src/kratos-demo/cmd [13:59:41]
→ go build main.go 
go: finding github.com/bilibili/kratos/pkg/log latest
go: finding github.com/bilibili/kratos/pkg/conf/paladin latest
go: finding github.com/bilibili/kratos/pkg latest
go: finding github.com/bilibili/kratos/pkg/conf latest
go: finding github.com/bilibili/kratos latest
go: downloading github.com/bilibili/kratos v0.0.0-20190425061354-bd2d576848f4
go: extracting github.com/bilibili/kratos v0.0.0-20190425061354-bd2d576848f4
go: golang.org/x/net@v0.0.0-20190311183353-d8887717615a: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181201002055-351d144fa1fc: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180606202747-9527bec2660b: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/crypto@v0.0.0-20190123085648-057139ce5d2b: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/time@v0.0.0-20190308202827-9d24e82272b4: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: golang.org/x/tools@v0.0.0-20190328211700-ab21143f2384: unrecognized import path "golang.org/x/tools" (https fetch: Get https://golang.org/x/tools?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: google.golang.org/grpc@v1.20.1: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 173.194.75.141:443: i/o timeout)
go: error loading module requirements

**Comment by token01** [comment]
是否可以加入 goproxy.io  这能防止被墙的可能性 @felixhao @tonyboxes @Terry-Mao @HarrisonXi

**Comment by tonyboxes** [comment]
可以拉一下最新的代码，已经加上go.mod已经加上了replace mirror

**Comment by token01** [comment]
已经拉的是最新的代码了 貌似还不行 看到go.mod 里的了

**Comment by token01** [comment]
go build  main.go
go: finding github.com/bilibili/kratos/pkg/conf/paladin latest
go: finding github.com/bilibili/kratos/pkg/log latest
go: finding github.com/bilibili/kratos/pkg/conf latest
go: finding github.com/bilibili/kratos/pkg latest
go: finding github.com/bilibili/kratos latest
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
go: finding golang.org/x/sys v0.0.0-20180606202747-9527bec2660b
go: finding golang.org/x/crypto v0.0.0-20190123085648-057139ce5d2b
go: finding golang.org/x/tools v0.0.0-20190311212946-11955173bddd
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
go: golang.org/x/sys@v0.0.0-20180606202747-9527bec2660b: git fetch -f https://go.googlesource.com/sys refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/sunzhenya/Work/go/pkg/mod/cache/vcs/76a8992ccba6d77c6bcf031ff2b6d821cf232e4ad8d1f2362404fbd0a798d846: exit status 128:
	error: RPC failed; curl 18 transfer closed with outstanding read data remaining
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unknown revision ebe1bf3edb33
go: golang.org/x/net@v0.0.0-20181201002055-351d144fa1fc: git fetch -f https://go.googlesource.com/net refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/sunzhenya/Work/go/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	error: RPC failed; curl 18 transfer closed with outstanding read data remaining
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed
go: golang.org/x/net@v0.0.0-20190311183353-d8887717615a: unknown revision d8887717615a
go: golang.org/x/tools@v0.0.0-20190311212946-11955173bddd: git fetch -f https://go.googlesource.com/tools refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/sunzhenya/Work/go/pkg/mod/cache/vcs/b44680b3c3708a854d4c89f55aedda0b223beb8d9e30fba969cefb5bd9c1e843: exit status 128:
	error: RPC failed; curl 18 transfer closed with outstanding read data remaining
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed
go: golang.org/x/tools@v0.0.0-20190328211700-ab21143f2384: unknown revision ab21143f2384

**Comment by tonyboxes** [comment]
我清理了pkg/mod，使用最新的代码，kratos、kratos-demo、自生成项目，看着都是正常；
帮忙cat go.mod看看，还有go mod项目不应该放在gopath里面的

**Comment by xiaojia21190** [comment]
这个有相应的解决方法吗

**Comment by tonyboxes** [comment]
cat go.mod
go version
go env

先提供下环境信息看看，最新代码用go 1.12可以直接跑的

**Comment by xiaojia21190** [comment]
module kratos-demo

go 1.12

require (
        github.com/bilibili/kratos v0.0.0-20190417043059-a08e0f771592
        github.com/gogo/protobuf v1.2.1
        github.com/golang/protobuf v1.3.1
        golang.org/x/net v0.0.0-20190420063019-afa5a82059c6
        google.golang.org/grpc v1.20.1
)

replace (
        cloud.google.com/go => github.com/googleapis/google-cloud-go v0.26.0
        golang.org/x/crypto => github.com/golang/crypto v0.0.0-20190123085648-057139ce5d2b
        golang.org/x/lint => github.com/golang/lint v0.0.0-20181026193005-c67002cb31c3
        golang.org/x/net => github.com/golang/net v0.0.0-20190311183353-d8887717615a
        golang.org/x/oauth2 => github.com/golang/oauth2 v0.0.0-20180821212333-d2e6202438be
        golang.org/x/sync => github.com/golang/sync v0.0.0-20181108010431-42b317875d0f
        golang.org/x/sys => github.com/golang/sys v0.0.0-20180905080454-ebe1bf3edb33
        golang.org/x/text => github.com/golang/text v0.3.0
        golang.org/x/time => github.com/golang/time v0.0.0-20190308202827-9d24e82272b4
        golang.org/x/tools => github.com/golang/tools v0.0.0-20190328211700-ab21143f2384
        google.golang.org/appengine => github.com/golang/appengine v1.1.0
        google.golang.org/genproto => github.com/google/go-genproto v0.0.0-20180817151627-c66870c02cf8
        google.golang.org/grpc => github.com/grpc/grpc-go v1.20.1
)

go version go1.12.4 windows/amd64


go version go1.12.4 windows/amd64
PS D:\GoProject\src\kratos-demo> go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\jws\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\GoProject
set GOPROXY=
set GORACE=
set GOROOT=E:\Go
set GOTMPDIR=
set GOTOOLDIR=E:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\jws\AppData\Local\Temp\go-build559834718=/tmp/go-build -gno-record-gcc-switches

**Comment by felixhao** [comment]
@token01 @xiaojia21190 拉完kratos-demo最新还是mod错误吗？不行QQ群：716486124里具体讨论看看到底问题出在哪里。

**Comment by FireTercel** [comment]
@token01 当我把项目放在GOPATH里面，并在kratos-demo\cmd 执行go build 也会报你这个错误，拷贝到其他目录下执行就正常了。

**Comment by tonyboxes** [comment]
那应该是go mod 为auto了，需要GO111MODULE=on才是启用

**Comment by FireTercel** [comment]
@tonyboxes 是这个问题，使用 set GO111MODULE=on 命令解决这个问题。否则没在GOPATH目录下面会找不到项目里面的依赖。

**Comment by wakaryry** [comment]
golang.org的都下不下来，可以换成github的包吗？
