### ISSUE TITLE
kratos-tool使用protoc的问题

### ISSUE THREAD

**Issue by github-yxb** [bilibili/kratos#152]
kratos-demo使用了gomod，所有的依赖项都是放在 GOPATH/pkg/mode 目录下。  
但使用kratos tool protoc api.proto 命令时，protoc的命令是去引用GOPATH/src 目录下的依赖  
如:  
`go/src/github.com/bilibili/kratos/third_party`

是有意这样设计的呢还是这是个问题？

**Comment by tonyboxes** [comment]
现在是配置了这几个proto目录：
* $GOPATH/src
* $KRATOS/third_party
* $PROJECT/api

除了使用protoc其实直接使用protobuf官方的也是可以的，效果一致~
