### ISSUE TITLE
配置中心部分如何对接市面上现有的配置中心服务?

### ISSUE THREAD

**Issue by Colstuwjx** [bilibili/kratos#154]
如题，有看到paladin sdk的部分，目前官方示例是file client，然后fsnotify会watch文件变化，并产出对应的event，那么对接其他配置中心服务是另外编写一个client来做？

还有一个问题是，paladin目前的写法不支持多namespace或者多cluster，这块该怎么考虑？
谢谢！

**Comment by tonyboxes** [comment]
hi jx, 目前我们是通过ZONE/DEPLOY_ENV/VERSION进行区分配置环境，后面会进行支持YAML格式；

对于namespace或者多cluster用法，有没有怎样的用法和建议的？

**Comment by Colstuwjx** [comment]
仔细想了下，以 [apollo](https://github.com/ctripcorp/apollo) 为例，cluster 应该等同于paladin的ZONE，然后namespace目前paladin的话就是对应各个不同的文件。apollo的话可以拉取和订阅多个namespace的配置，比如mysql配置是一块，redis是一块，然后部门层面公共的一些配置是一块，这个目前paladin可以订阅一个目录下的文件，我觉得是OK的，可能有一点差异的地方在于paladin目前的watch对象可以到key，而apollo watch的是namespace。

目前我觉得可能有三种方案：

1、还是base文件，各种配置中心server仍然是实现“下载文件-订阅变化-更新文件”这样的逻辑，paladin仍然还是使用file client来订阅文件变化，然后reload配置；
2、各种配置中心server实现client所需的接口方法，然后对接到paladin；
3、paladin是一个可选方案，kratos增加一些最佳实践，讲解其他配置中心怎么和kratos一起工作

我个人倾向于方案一，方案二的话各个配置中心server的设计和实现存在差异，这些做抽象封装的话维护成本可能会比较高，方案三的话可能就是kratos组件设计方面的考虑了，kratos推荐的是乐高积木一样的组合方式，还是脚手架+适配器的模式。

**Comment by Terry-Mao** [comment]
@Colstuwjx 尴尬了，我们内部其实是VERSION（这个其实随意了，一些历史原因），Zone 是机房的概念。
我们弱化了namespace的概念，太复杂了。一个app/应用对应一个大的配置文件集合，每个集合你可以认为是key-value对，所以namespace对应为我们的key。

目前我们内部 1 + 2，实现了内部配置中心的接口的client，把配置文件下载到了本地，仅仅为了多冗余一份，避免集中式的配置中心故障。但是所有动态更新是2类似的做法做的。

现在只提供了file、mock两种实现，后续可以贡献MR，比如适配appollo，后续逐渐会开源内部配置中心出来。

**Comment by Terry-Mao** [comment]
两个改法：

1、类似gRPC Resolver 那种 实现一个Builder，自己注入实现，基于名字；

2、Init 方法 提供自定义实现暴露Reporter 接口；

这样方便go mod引入的人来扩展和替换，而不是在kratos 代码目录里去改

另外可以考虑内部直接支持 zipkin、jagging

**Comment by Colstuwjx** [comment]
已经提了一个PR  #340 ，集成了对 [apollo配置中心](https://github.com/ctripcorp/apollo) 的支持。

**Comment by Terry-Mao** [comment]
@Colstuwjx ，还需要支持，哈哈。目前paladin 有抽象设计，但是没有Builder，方便外部代码可以注入来初始化

**Comment by Colstuwjx** [comment]
apollo的PR已经合并，类似的远程配置中心也可以按照apollo的实现方式自行实现。
