### ISSUE TITLE
kratos-demo 里的api.proto 导入其他proto的文件的路径是否要修改？

### ISSUE THREAD

**Issue by busyfree** [bilibili/kratos#158]
本地开发环境，分2个gopath，一个是用于存第三方库的，一个是开发目录
demo创建使用 `kratos new kratos-demo --proto `
demo里的路径
```
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
```

文件绝对路径
```
import "/Users/**/Documents/golib/src/github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/empty.proto";
import "/Users/**/Documents/golib/src/github.com/bilibili/kratos/tool/protobuf/pkg/extensions/google/api/annotations.proto";
```
执行生成pb文件路径错误
![image](https://user-images.githubusercontent.com/504251/59491606-ad5a9700-8eb9-11e9-878f-33a63fce59af.png)

相对路径导入
```
import "./../../../../golib/src/github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/empty.proto";
import "./../../../../golib/src/github.com/bilibili/kratos/tool/protobuf/pkg/extensions/google/api/annotations.proto";
```
执行生成pb文件路径错误
![image](https://user-images.githubusercontent.com/504251/59492420-84d39c80-8ebb-11e9-920a-18ec38a79c34.png)

**Comment by tonyboxes** [comment]
导致第三方proto，可以用这两种方式：
1、$gopath/src下面，`import "$other_project/api/api.proto`；
2、$project/api下面，`import "$project/api/xxx.proto`;

生成proto代码：
```shell
cd $gopath
kratos tool protoc $project/api/api.proto
```

>  理论上内部都会有一个proto共享仓库，可以直接放在gopath下面；

**Comment by busyfree** [comment]
感谢
