### ISSUE TITLE
调用RPC会出现下面这个问题,看遍文档也找不出解决方法

### ISSUE THREAD

**Issue by hsiar** [bilibili/kratos#159]
![image](https://user-images.githubusercontent.com/29941510/59492568-d2500980-8ebb-11e9-8551-bf24c6dff26b.png)

**Comment by hsiar** [comment]
使用direct和discovery都是一样的问题

**Comment by tonyboxes** [comment]
1、可以先更新一下kratos到v0.1.1：`go get -u github.com/bilibili/kratos/tool/kratos`；
2、gRPC可以通过 `direct` 或者 `discovery` 方法使用：https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/warden-resolver.md；
