### ISSUE TITLE
新手关于BladeMaster

### ISSUE THREAD

**Issue by codlin** [bilibili/kratos#165]
看到kratos，感觉挺不错的。
然后看介绍说使用了Gin于是找了半天，发现Gin已融进BladeMaster ;-) 
我能想到的优点是：
1. 可以根据自己的需求来修改，灵活性大
2. 可以在这个固定的版本上修改bug，优化性能，利于积累
但同时缺点也有，就是侵入性：
1. 如果Gin推出了新版本，而开发者刚好需要这些功能，是否可以很方便的merge进去

不知道官方对这个问题是什么看法？
谢谢

**Comment by realityone** [comment]
blademaster 对于 gin 更倾向于是定制化开发后的，因为 gin 的使用方式比较讨人喜欢，也便于集成更多各色各样的中间件，所以 blademaster 的原型就是基于 gin 来开发的。

但是因为 gin 里的某些功能或者设计不便于 bilibili 使用，或者有误用的可能，所以在此基础上去除了一部分功能和逻辑。

再对于线上服务而言，为了满足监控、稳定性需要，又在其核心处理流程里加入了部分逻辑，比如元数据 API、超时传递、服务染色等等。

实际上当前 gin 的核心处理流程已经没有太大的变化了，因此 blademaster 也几乎没有因为 gin 更新而导致核心逻辑发生的变更了。对于新功能而言，我更倾向于能否通过中间件的形式集成入你的应用，gin 或 blademaster 里的中间件编写真的非常简单。

也有部分功能是必须修改核心逻辑才可以集成的，比如 [Parameters in path](https://github.com/gin-gonic/gin#parameters-in-path)。最早设计 blademaster 的时候因为想避开这种模式的 API，所以直接使用了标准库里的 mux。但是现在也有支持的计划，所以也会人工和 gin 的逻辑进行同步和测试。

希望可以帮你理解当前 blademaster 的设计。

**Comment by codlin** [comment]
@realityone 非常感谢~~
