### ISSUE TITLE
关于配置管理的机制

### ISSUE THREAD

**Issue by snowwolf007cn** [bilibili/kratos#166]
我看了一下框架，似乎配置管理部分是写死的。
如果在开发过程中，用户需要扩展框架，注入一些自定义的组件和组件配置，那么，如何动态管理配置，如何进行扩展呢？

**Comment by Terry-Mao** [comment]
是说配置管理，如何使用自己的配置中心的意思吗？

**Comment by snowwolf007cn** [comment]
> 是说配置管理，如何使用自己的配置中心的意思吗？

并不是需要自定义的配置中心，而是说，如果我想引入一个自己开发的组件，这个组件会有一些配置项，应该落在哪儿？

**Comment by Terry-Mao** [comment]
如果是一个独立的组件，可以独立的一个key-value ，比如独立的toml/yml文件

**Comment by snowwolf007cn** [comment]
比如说，用户自己编写了一个插件，并且提供了一个配置文件放到了配置里。可否通过配置文件的变更，自动在程序启动的时候发现有新的插件引入，并且初始化一个插件单例到内存里呢？

**Comment by Terry-Mao** [comment]
plugin机制么？风险很大的， @snowwolf007cn

**Comment by snowwolf007cn** [comment]
@Terry-Mao 的确，但是这样可以比较有效的扩展框架的功能和适用场景。
