### ISSUE TITLE
api.proto中无法找到 gogoproto/gogo.proto、google/api/annotations.proto

### ISSUE THREAD

**Issue by lvxj** [bilibili/kratos#170]
如题，api.proto中无法找到 gogoproto/gogo.proto、google/api/annotations.proto，导致运行
 kratos tool protoc api.proto 时候报错：
gogoproto/gogo.proto: File not found.
api.proto: Import "gogoproto/gogo.proto" was not found or had errors.

**Comment by tonyboxes** [comment]
本地的kratos应该是老版本，可以更新一下kratos看看：
```
go get -u github.com/bilibili/kratos/tool/kratos
go get -u github.com/bilibili/kratos/tool/protobuf/protoc-gen-bm
go get -u github.com/bilibili/kratos/tool/protobuf/protoc-gen-bswagger
go get -u github.com/gogo/protobuf/protoc-gen-gofast
```

**Comment by lvxj** [comment]
我是今天下载最新的版本，刚才把你这个又执行了一次 ，还是不行～ 应该不是老版本的原因

**Comment by lvxj** [comment]
我是使用的 kratos new kratos-seven --proto 这个命令创建的项目，然后打开api目录下的api.proto就显示我说的那个问题

**Comment by tonyboxes** [comment]
估计是这个protoc之前安装了旧版本，我先fix自动取最新的tool：
`go get -u github.com/bilibili/kratos/tool/kratos-protoc`

**Comment by lvxj** [comment]
你提供的这个命令我刚也执行了，很奇怪，我重新把所有依赖全删了，重新下载，现在是可以使用的，只不过idea红色报错标记：
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/empty.proto";
import "google/api/annotations.proto";

这3个import ，第二个idea没有报错，第一个和第三个idea显示报错没有找到，但是实际不影响使用，只是idea报错红色，不晓得是哪里的问题

**Comment by tonyboxes** [comment]
应该是`kratos-protoc`版本的问题，已经fix版本自动更新的，idea应该没找着proto_path而已，protoc也是手动指定的

**Comment by ycg000344** [comment]
目前在 vscode 還存在這個 import 的問題，但是可以生成文件，請問怎麽解決呀，感謝。
```
Import "google/api/annotations.proto" was not found or had errors.
```

**Comment by luxuze** [comment]
> 目前在 vscode 還存在這個 import 的問題，但是可以生成文件，請問怎麽解決呀，感謝。
> 
> ```
> Import "google/api/annotations.proto" was not found or had errors.
> ```

+1

**Comment by Jungle-Leung** [comment]
> 目前在 vscode 還存在這個 import 的問題，但是可以生成文件，請問怎麽解決呀，感謝。
> 
> ```
> Import "google/api/annotations.proto" was not found or had errors.
> ```

+1

**Comment by luxuze** [comment]
配置里面加上这个就好了, 注意地址要对: (当时研究了好久, 真tm坑)
`
{
  "protoc": {
    "options": [
      "--proto_path=$(GOPATH)/src/github.com/go‌​go/protobuf/protobuf‌​:"
    ]
  },
}
`

**Comment by Hangzhi** [comment]
@luxuze 想问这个可以用go mod 管理吗？还是一定要下载 gogo 在 GOPATH？

**Comment by longhopefor** [comment]
> 配置里面加上这个就好了, 注意地址要对: (当时研究了好久, 真tm坑)
> `{ "protoc": { "options": [ "--proto_path=$(GOPATH)/src/github.com/go‌​go/protobuf/protobuf‌​:" ] }, }`

问下这个配置是加在哪里的呢，刚也遇到这个问题了， 感觉好坑啊，官方也没个标准说明

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/123961509-0505c580-d9e3-11eb-8cc6-9e9c9cf539df.png) @longhopefor 这是vscode

**Comment by longhopefor** [comment]
> ![image](https://user-images.githubusercontent.com/23260162/123961509-0505c580-d9e3-11eb-8cc6-9e9c9cf539df.png) @longhopefor 这是vscode
好的，谢谢，已经解决了
