### ISSUE TITLE
能否使用Any、Struct.Value之类的类型

### ISSUE THREAD

**Issue by opteacher** [bilibili/kratos#173]
添加如上protobuf自带的复合类型，会报错缺少：
* Size
* MarshalTo
* Unmarshal
如可以引入和使用这些类型，应该怎么生成啊？求教~

**Comment by yundequanshi** [comment]
> 添加如上protobuf自带的复合类型，会报错缺少：
> 
> * Size
> * MarshalTo
> * Unmarshal
>   如可以引入和使用这些类型，应该怎么生成啊？求教~

你好，这个怎么解决的呀

**Comment by haoyue0603** [comment]
@yundequanshi 除了这个问题，还有服务反射也有问题，可以试试用原生 protobuf .
