### ISSUE TITLE
kratos new demo4 --proto 报错

### ISSUE THREAD

**Issue by greyireland** [bilibili/kratos#174]
➜ kratos new demo4 --proto
2019/06/21 20:46:24 protoc --proto_path=/Users/xiaodong/go/src --proto_path=/Users/xiaodong/go/src/github.com/bilibili/kratos/third_party --proto_path=/Users/xiaodong/go/src --bm_out=explicit_http=true:. demo4/api/api.proto
demo4/api/api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
exit status 1
Project: demo4
Owner: 
WithGRPC: true
Directory: /Users/xiaodong/go/src/demo4

The application has been created.

**Comment by tonyboxes** [comment]
现在安装的protobuf是那个版本的？
可以手动执行protoc看看：
```
cd %GOPATH%
protoc --proto_path=/Users/xiaodong/go/src --proto_path=/Users/xiaodong/go/src/github.com/bilibili/kratos/third_party --bm_out=explicit_http=true:. demo4/api/api.proto
```

**Comment by greyireland** [comment]
```
➜  src protoc --proto_path=/Users/xiaodong/go/src --proto_path=/Users/xiaodong/go/src/github.com/bilibili/kratos/third_party --bm_out=explicit_http=true:. demo4/api/api.proto
demo4/api/api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

➜  src protoc --version
libprotoc 3.3.0

➜  src kratos --version
kratos version 0.0.1
```

**Comment by tonyboxes** [comment]
这个protobuf版本很旧了，可以升级到3.6.x以上版本不的？

**Comment by greyireland** [comment]
安装protoc 3.8解决问题了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
