### ISSUE TITLE
你好，我这边windows电脑 使用你们的框架，总是出错呢

### ISSUE THREAD

**Issue by dotcool** [bilibili/kratos#175]
go: extracting github.com/golang/text v0.3.0
swagger: 安装成功!
运行 swagger 出错: exec: "D:\\repo\\edus;D:\\repo\\edus\\vendor;\\bin\\swagger": file does not exist

protoc: 安装成功!
运行 protoc 出错: exec: "D:\\repo\\edus;D:\\repo\\edus\\vendor;\\bin\\kratos-protoc": file does not exist

这个路径 D:\\repo\\edus是我本机的goroot。希望可以解答一下哦。感谢

用mac执行创建 --proto也会提示错误

2019/06/25 00:13:49 protoc --proto_path=/Users/dotcoolgirl/go/src --proto_path=/Users/dotcoolgirl/go/pkg/mod/github.com/bilibili/kratos@v0.1.0/third_party --proto_path=/Users/dotcoolgirl/go/src --bm_out=explicit_http=true:. kratos-pro/api/api.proto
kratos-pro/api/api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

执行kratos tool提示已经安装了所有工具，但是使用的时候却不行

kratos tool protoc --swagger api.proto
kratos tool protoc ./api.proto
这样都不行。提示这个

api.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
exit status 1

**Comment by CocoaZX** [comment]
same problem

**Comment by CocoaZX** [comment]
运行 genproject 出错: exec: "E:\\codeIDE\\go\\goPath;E:\\codeIDE\\go\\goPath\\bin\\bin\\kratos-gen-project": file does not exist
panic: exec: "E:\\codeIDE\\go\\goPath;E:\\codeIDE\\go\\goPath\\bin\\bin\\kratos-gen-project": file does not exist

**Comment by hbyexplore** [comment]
运行 genproject 出错: exec: "E:\codeIDE\go\goPath;E:\codeIDE\go\goPath\bin\bin\kratos-gen-project": file does not exist
panic: exec: "E:\codeIDE\go\goPath;E:\codeIDE\go\goPath\bin\bin\kratos-gen-project": file does not exist
