### ISSUE TITLE
创建工程加上参数--proto失败

### ISSUE THREAD

**Issue by SZT0728** [bilibili/kratos#182]
我执行go get -u github.com/bilibili/kratos/tool/kratos命令后创建工程，提示如下失败：
➜  src kratos new kratos-demo2 --proto
go get -u github.com/bilibili/kratos/tool/kratos-protoc

_- 1. 运行 protoc 出错: chdir bin: no such file or directory
- 2. 运行 protoc 出错: fork/exec bin/kratos-protoc: no such file or directory_

Project: kratos-demo2
Owner:
WithGRPC: true
Directory: /Users/mac/go/src/kratos-demo2

The application has been created.

同时我查看kratos工具：kratos tool也显示如下：
kratos(未安装): Kratos工具集本体 Author(kratos) [2019/06/21]
protoc(未安装): 快速方便生成pb.go的protoc封装，windows、Linux请先安装protoc工具 Author(kratos) [2019/06/21]
swagger(未安装): swagger api文档 Author(goswagger.io) [2019/05/05]
genbts(未安装): 缓存回源逻辑代码生成器 Author(kratos) [2019/05/05]
genmc(未安装): mc缓存代码生成 Author(kratos) [2019/05/05]

安装工具: kratos tool install demo
执行工具: kratos tool demo
安装全部工具: kratos tool install all

都显示工具未安装，但是kratos tool install 安装就出错

**Comment by tonyboxes** [comment]
环境配置GOBIN指向问题，或者GOBIN没有加到GOPATH中
