### ISSUE TITLE
服务注册与发现容易panic挂掉

### ISSUE THREAD

**Issue by dcsunny** [bilibili/kratos#183]
以下是其中一处:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4637eff]

goroutine 30 [running]:
github.com/bilibili/kratos/pkg/naming/discovery.(*Discovery).polls(0xc0002d2c80, 0x49c2120, 0xc0003107c0, 0x2, 0x0, 0x0)
       /go/src/bilibili/kratos/pkg/naming/discovery/discovery.go:598 +0x9df
github.com/bilibili/kratos/pkg/naming/discovery.(*Discovery).serverproc(0xc0002d2c80)
       /go/src/bilibili/kratos/pkg/naming/discovery/discovery.go:518 +0x16f
created by github.com/bilibili/kratos/pkg/naming/discovery.(*Discovery).Build.func1
        /go/src/bilibili/kratos/pkg/naming/discovery/discovery.go:250 +0x3e
exit status 2

**Comment by lintanghui** [comment]
做了啥操作，执行了啥步骤，相关配置信息是啥，麻烦把问题描述清楚

**Comment by dcsunny** [comment]
我是利用github.com/bilibili/discovery 搭了一个discovery服务，接着写了两个demo服务，配置是默认配置，除了改端口保证两个服务可以正常启动。
注册和client的代码是下面
```
//client 
func init() {
	// NOTE: 注意这段代码，表示要使用discovery进行服务发现
	// NOTE: 还需注意的是，resolver.Register是全局生效的，所以建议该代码放在进程初始化的时候执行
	// NOTE: ！！！切记不要在一个进程内进行多个不同中间件的Register！！！
	// NOTE: 在启动应用时，可以通过flag(-discovery.nodes) 或者 环境配置(DISCOVERY_NODES)指定discovery节点
	resolver.Register(discovery.Builder())
}

// NewClient new member grpc client
func NewClient(cfg *warden.ClientConfig, opts ...grpc.DialOption) (api.DemoClient, error) {
	client := warden.NewClient(cfg, opts...)
	conn, err := client.Dial(context.Background(), "discovery://default/"+AppID)
	if err != nil {
		return nil, err
	}
	// 注意替换这里：
	// NewDemoClient方法是在"api"目录下代码生成的
	// 对应proto文件内自定义的service名字，请使用正确方法名替换
	return api.NewDemoClient(conn), nil
}

func Register(appid string, ip string, port string) context.CancelFunc {
	conf := &discovery.Config{
		Region: "region01",
		Nodes:  []string{"127.0.0.1:7171"},
		Zone:   "sh001",
		Env:    "dev",
	}
	//ip := "" // NOTE: 必须拿到您实例节点的真实IP，
	//port := "" // NOTE: 必须拿到您实例grpc监听的真实端口，warden默认监听9000
	dis := discovery.New(conf)
	ins := &naming.Instance{
		Zone:  "sh001",
		Env:   "dev",
		AppID: appid,
		Addrs: []string{
			"grpc://" + ip + ":" + port,
		},
		LastTs:   time.Now().Unix(),
		Metadata: map[string]string{"weight": "10"},
	}
	cancel, err := dis.Register(context.Background(), ins)
	if err != nil {
		panic(err)
	}
	return cancel
}

//两个服务相互调用的代码（在main里面写了如下注册和调用代码）
_cancel := dis.Register("test1", "127.0.0.1", "9000")
	go func() {
		time.Sleep(time.Second * 10)
		wccfg := &warden.ClientConfig{}
		client, err := dis.NewClient(wccfg)
		if err != nil {
			fmt.Println(err)
			return
		}
		reply, err := client.SayHello(context.Background(), &api.HelloReq{
			Name: "test1",
		})
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println(reply)
	}()
```
1、kratos new test2 --proto 创建服务，并修改基本配置
2、执行go run main.go -conf ../configs -http.perf tcp://0.0.0.0:2333. 
3、test1服务调用test2服务的rpc服务，test2调用test1的rpc服务。
4、 接着control+c关闭test2服务，test1服务就会出现上面那个panic了

**Comment by lintanghui** [comment]
看起来是由于test2关闭了导致test1拿不到test2的节点discovery返回空导致sdk里空指针报错了，需要优化下这里的处理逻辑
