### ISSUE TITLE
blademaster对router更加友好的支持

### ISSUE THREAD

**Issue by DemonsLu** [bilibili/kratos#188]
问题描述：
我们在设计restful api时，经常遇到的一种情况是：对相同资源的不同操作，请求的url是相同的，而请求类型不同。

我注意到blademaster在添加路由时，底层逻辑的addRoute方法中的判断，首先是engine.metastore[path]["method"] = method 这句话，它会导致注册多个相同url不同请求方法时，后面的会覆盖前面的，造成内容丢失；然后更加致命的是，bm的mux使用的是原生的http.ServeMux，而它是不支持HTTP方法匹配的，这会导致我根本无法注册相同URL不同请求方法的多个router，经过测试，它会直接报panic，而panic的信息跟踪，发现是原生的错误。go源码的错误信息如下：

	if _, exist := mux.m[pattern]; exist {
		panic("http: multiple registrations for " + pattern)
	}

源码位置： net/http/server.go 的 func (mux *ServeMux) Handle(pattern string, handler Handler) 方法  
		  go version: 1.12.5

建议： 不要使用原生的mux struct，可以切换为Gorilla Mux，它与ServeMux兼容性很好，而且不光支持HTTP方法匹配，还可以支持url正则匹配。

**Comment by realityone** [comment]
Hi @DemonsLu,

Thanks for your contributions!

实际上在内部使用的过程中，我们当时试图避免用户设计 API 时使用多 method 的方式。最开始因为实践 RESTful API 时也产生了许多与各端对接上的意外，因此最早设计 bm 时就避开了这种 API 模式，所以权衡之后没有使用 gorilla mux 和许多类似功能的组件。实际上 bm 内也有很多基于当前路由模式而规划的功能，比如 `metadata` 的数据结构就是其中之一。

目前内部对多 method 与多模式匹配路由也慢慢有了进一步的讨论，之后可能会以另一种形式来实现类似功能。

**Comment by DemonsLu** [comment]
感谢回复～ 我个人的一点看法是：如果是直接2c的接口，可能使用restful API确实会有些坑，因为2c接口的重点一般都是面向行为的；但是对于开发一个公司内部的后台管理系统来讲，因为绝大部分接口都是面向资源的，使用restful API会非常便利。 最后，期待你们的新版本～

**Comment by captainblue2013** [comment]
比较关注这个issue，我认为标准的http规范下的restful，是应该彻底支持的。
希望能把这个优先级提高。

**Comment by DemonsLu** [comment]
@realityone @captainblue2013 这样吧，我重新把这个issue打开，大家如果对这个需求有什么建议和看法，可以一起讨论~  #189 是我针对这个问题提的解决方案

**Comment by captainblue2013** [comment]
@DemonsLu 我也是这个思路，区别是我是在engine里增加一个 gmux，
 再一个就是加入一条判断 method + path是否重复注册的问题，不直到有没有意义。 #193

**Comment by felixhao** [comment]
感谢建议，内部已经在灰度：
1. 多method同一url支持
2. path param支持
