### ISSUE TITLE
使用discovery服务注册时warden无法获取到server的地址

### ISSUE THREAD

**Issue by QRiner** [bilibili/kratos#204]
## 环境
**discovery版本**
v1.1
**kratos版本**
commit c232ca8ff6d0fdbe9aa1ee75ee245a410246eb81

## 现象
之前版本的discovery不存在这个问题，更新到discovery 1.1后在http请求中传多个appid时(?appid=foo&appid=bar)，discovery只返回第一个appid的节点信息。在client启动调用时会同时请求infra.discovery和调用服务的信息，这时会导致调用失败。

## 原因
因为看到discovery1.1使用了kratos的blademaster，怀疑是兼容问题。通过单步发现问题在github.com/bilibili/kratos/pkg/net/http/blademaster/binding/form_mapping.go中的setWithProperType方法，如果struct中某个field包含 `json:"appid,split"` ，请求就只会拿第一个`val[0]`处理：
```code golang
case reflect.Slice:
	if option.Contains("split") {
		val = strings.Split(val[0], ",")
        }
```
## fix
把discovery中相关地方的`,split`去掉，或者在form_mapping.go中循环处理所有的`val`

**Comment by lintanghui** [comment]
使用split时  使用appid=foo,bar 进行参数传递
