### ISSUE TITLE
关于跨域的问题

### ISSUE THREAD

**Issue by C-isCoder** [bilibili/kratos#208]
看到 kratos 内部中间件有个 `blademaster` cors.go 的实现。貌似在非简单请求里面不管用。请指导一下。
```golang

var (
	svc   *service.Service
	_cors = []string{"*"}
)
func initRouter(e *bm.Engine) {
	e.Ping(ping)
	//e.Use(mid.MyCors())
	e.Use(bm.CORS(_cors))
	u := e.Group("/user")
	{
		u.POST("/v1/login", handlerLogin)
		u.POST("/v1/register", handlerRegister)
	}
	d := e.Group("/drug", mid.Token())
	{
		d.POST("/v1/search", handlerSearch)
	}
}
```
下面是我自己写的，不知道这种方式对不对，想着用 kratos 内置更方便。

``` golang
func MyCors() bm.HandlerFunc {
	return func(ctx *bm.Context) {
		origin := ctx.Request.Header.Get("Origin")
		if ctx.Request.Method == http.MethodOptions && origin != "" {
			ctx.Writer.Header().Add("Access-Control-Allow-Origin", origin)
			ctx.Writer.Header().Add("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
			ctx.Writer.Header().Add("Access-Control-Allow-Credentials", "true")
			ctx.Writer.Header().Add("Access-Control-Allow-Headers", "Content-Type,"+
				"X-Requested-With,Access-Control-Allow-Credentials,User-Agent,Content-Length,Authorization")
			ctx.AbortWithStatus(200)
		} else if origin != "" {
			ctx.Writer.Header().Add("Access-Control-Allow-Origin", origin)
		}
		return
	}
}
```

还有个问题，想在生产环境用。kratos 自己本身接触 golang 不是很久。想用 kratos 开发单体应用，后期再拆分。前期主要自己 hold 不住，单体应用用 protoc 的方式成多个 http 有啥办法吗

**Comment by realityone** [comment]
这个 CORS 实现目前适用于 bilibili 内部，你可以详细说下你遇到的问题现象。

**Comment by C-isCoder** [comment]
问题一：bilibili 内部的 CORS 不支持“非简单请求” 的跨域。我这边用的是 Header 里面传 token 所以前端浏览器请求就是“非简单请求”跨域。预检过后每次请求都要服务端返回 Origin 头信息。bilibili 内部的 CORS 能否修改一下，我们也能用。
> 4.3 浏览器的正常请求和回应
> 一旦服务器通过了"预检"请求，以后每次浏览器正常的CORS请求，就都跟简单请求一样，会有一个Origin头信息字段。服务器的回应，也都会有一个Access-Control-Allow-Origin头信息字段。

问题二：我是想用 kratos 开发单体应用，所有的服务想写在一个 api 文件夹内，用模块名分类。用 kratios tool 生成模版代码的时候 ，路由注册没法搞了，`api.proto` 里面声明的 service 类型不一致。请问我这种情况怎么处理，目前是没有用生成模版的方式直接写在路由里面。或者对于 kratios 开发单体应用又啥件建议吗。是不是也可以整个项目的所有 api 都写到一个 `api.proto` 里。感谢回复

**Comment by skyhotqin** [comment]
一样遇到这个问题，不过在新版的设计（旧版没用过）中，可以通过在internal/server 中针对所用的 transport的类型 加上对应的CORS即可，比如直接Kratos生成的pd代码中是用 gorilla 的，所以在internal/server/http.go 中 ，变更代码为
```go
// 在import处加入
import "github.com/gorilla/handlers"
 ....
 ....
r := YourAPI.NewXXXHandler(xxx, m)
	headersOk := handlers.AllowedHeaders([]string{"Content-Type", "X-Requested-With"})
	originsOk := handlers.AllowedOrigins([]string{"*"})
	methodsOk := handlers.AllowedMethods([]string{"GET", "POST","PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"})
	r = handlers.CORS(headersOk, originsOk, methodsOk)(r)
	srv.HandlePrefix("/", r)
```

**Comment by lulyqqqq** [comment]
现在跨域配置hostorigin是不支持通配符吗？

**Comment by whg517** [comment]
ref: https://github.com/Windfarer/kratos-realworld
