### ISSUE TITLE
考虑为kratos增加一个轻量版的分布式cron吗？

### ISSUE THREAD

**Issue by LibiChai** [bilibili/kratos#230]
很多微服务里需要依赖各类计划任务，如果用容器部署的话需要使用系统级的cron单独进行配置。

如果在框架里增加分布式的cron模块，开发者就不需要关注运维层面的cron的配置，只需要按服务在代码或者配置文件内配置定时任务，并且在容器复制实例扩容时不会产生任务重复执行等问题，可以很大程度降低运维复杂度。

**Comment by captainblue2013** [comment]
看看  https://github.com/jasonlvhit/gocron  最近出来，挺好的

**Comment by LibiChai** [comment]
> 看看 https://github.com/jasonlvhit/gocron 最近出来，挺好的
这个是单节点的，当同一个服务需要同时部署多个节点时，服务内的定时任务每个节点都会执行一次。

**Comment by Terry-Mao** [comment]
这里面有几个思路，建议参考：

1、基于k8s cronjob 来实现；
2、参考Google Cron，基于Raft/Paxos来做秒级HA的Cron服务，有难度；

短期我建议先看看基于k8s来做？

**Comment by LibiChai** [comment]
基于k8s的话是不是代表框架对k8s有强依赖，当服务编排没有使用k8s的话这个功能还是不可用。

**Comment by captainblue2013** [comment]
> 这里面有几个思路，建议参考：
> 
> 1、基于k8s cronjob 来实现；
> 2、参考Google Cron，基于Raft/Paxos来做秒级HA的Cron服务，有难度；
> 
> 短期我建议先看看基于k8s来做？

我也建议用k8s，天然的cronjob类型deployment

**Comment by captainblue2013** [comment]
另外，我看楼主的描述，反而不像是cron，而有点像消息队列的消费者

**Comment by LibiChai** [comment]
分布式定时任务调度，和消息队列没有关系。消费者执行时间取决于生产者产生数据的时间和队列执行情况，定时任务是要精确时间执行。

**Comment by Terry-Mao** [comment]
@LibiChai 目前可能只能做到kratos引入一个单机版本的crontab，类似Java Quartz。分布式的Cron作为基础库会有点重，可能适合独立一个单独的开源项目，你觉得呢？

**Comment by LibiChai** [comment]
嗯，单机版本的也可以，需要多节点时开发期间加上限定也能跑起来。

**Comment by Terry-Mao** [comment]
好，我们参考设计下

**Comment by guihouchang** [comment]
设计到哪里去了呢？
