### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by overstarry** [bilibili/kratos#231]
![image](https://user-images.githubusercontent.com/23260162/61630239-d2f96e00-acb9-11e9-896b-9f3166946682.png)

**Comment by tonyboxes** [comment]
直接clone代码看看，估计是go mod少了？

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/61631052-dee62f80-acbb-11e9-9c18-d6c19b43b83d.png)
也不行

**Comment by wx-shi** [comment]
我也是这个错误

**Comment by wx-shi** [comment]
master分支把go.mod replace去掉了 能安装了

**Comment by wx-shi** [comment]
@overstarry 你clone下来 需要切到v.0.2.0 然后 go mod tidy 再安装

**Comment by tonyboxes** [comment]
帮试试master是否可以，去掉了replace的
`go get -u github.com/bilibili/kratos/tool/kratos@master`

**Comment by tonyboxes** [comment]
要是@master正常，我再重新打个v0.2.1版本

**Comment by wx-shi** [comment]
@tonyboxes 
![image](https://user-images.githubusercontent.com/32156634/61681478-27dfc780-ad40-11e9-81e3-10d4badc7f7a.png)

**Comment by wx-shi** [comment]
@tonyboxes 不正常。。。 昨天我用master还正常，今天不行了
```
➜  ~ go get -u github.com/bilibili/kratos/tool/kratos@master
go: finding github.com/bilibili/kratos/tool/kratos master
go: finding github.com/bilibili/kratos/tool master
go: finding github.com/bilibili/kratos master
go: finding github.com/StackExchange/wmi latest
go: github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: parsing go.mod: missing module line
go: github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c: parsing go.mod: missing module line
go: finding github.com/cznic/mathutil latest
go: finding github.com/dgryski/go-farm latest
go get: error loading module requirements
```

**Comment by wx-shi** [comment]
@tonyboxes 
```
➜  kratos git:(master) go mod tidy
verifying github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	go.sum:     h1:qqbHyh8v60DhA7CoWK5oRCqLrMHRGoxYCSS9EjAz6Eo=
➜  kratos git:(master)
```

**Comment by overstarry** [comment]
@tonyboxes  新版本还是有些问题 
![image](https://user-images.githubusercontent.com/23260162/61792957-872cfd00-ae50-11e9-9ba8-23b0510f87f7.png)

**Comment by overstarry** [comment]
换阿里云的代理可以解决https://mirrors.aliyun.com/goproxy/

**Comment by overstarry** [comment]
删除gopath目录下mod的缓存，不使用https://goproxy.io,换个代理

**Comment by FlyingKirito** [comment]
我这边 
export GOPROXY=https://mirrors.aliyun.com/goproxy/
export GOPROXY=https://goproxy.cn/
export GOPROXY=https://goproxy.io/
三个代理全用了一遍都不行
