### ISSUE TITLE
如何创建代有tidb配置和客户端的demo工程？

### ISSUE THREAD

**Issue by albertlinux** [bilibili/kratos#232]
看到官网上提到了对TiDB的集成。但是看默认创建的项目里面数据访问层只有mysql，redis和memcache。想请教一下，如何生成带有tidb配置和客户端的demo工程呢？

**Comment by tonyboxes** [comment]
其实最终实现还是需要自己写逻辑，应该是需要什么模块自己引入到工程里就可以了

**Comment by albertlinux** [comment]
好的，谢谢您！我之前的设想是用kratos工具生成代码时，可以通过参数指定需要的数据库访问层代码，比如只生成mysql的，此外期待能够类似mysql生成tidb的配置文件tidb.toml，并自动在dao.go中添加对应的tidb的配置读取和连接初始化代码。
