### ISSUE TITLE
cannot load github.com/prometheus/client_model/go

### ISSUE THREAD

**Issue by shaojintian** [bilibili/kratos#243]
![image](https://user-images.githubusercontent.com/40530183/62182736-51c16b80-b38a-11e9-94cf-437a25b2d693.png)

**Comment by shaojintian** [comment]
go: creating new go.mod: module github.com/shaojintian/6.824
go: downloading github.com/prometheus/client_model v0.0.0-20190220174349-fd36f4220a90
build github.com/shaojintian/6.824/GoProjects/kratos-demo/cmd: cannot load github.com/prometheus/client_model/go: zip: not a valid zip file

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/FAQ.md

可以按这个FAQ试试
