### ISSUE TITLE
go: error loading module requirements

### ISSUE THREAD

**Issue by dongyule** [bilibili/kratos#245]
➜  cmd go build
go: github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: parsing go.mod: missing module line
go: github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c: parsing go.mod: missing module line
go: error loading module requirements
➜  cmd pwd
/Users/dongyule/go/src/kratos-demo/cmd

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/FAQ.md

可以按这个FAQ试试
