### ISSUE TITLE
部署不起来

### ISSUE THREAD

**Issue by xiawanyingtest** [bilibili/kratos#255]
1.流程
   进度前面的都成功了，包括protobuf生成
2.错误：
build kratos-demo/cmd: cannot load github.com/bilibili/kratos/pkg/cache/redis: open D:\work\goCode\src\kratos-demo\vendor\github.com\bilibili\kratos\pkg\cache\redis: The system cannot find the path specified.
3.其他问题
  redis密码怎么设置？
4.使用的管理工具是go modules
5.那个client没有生成相关的demo，
   能否给个例子
6.注册服务端口地址是多少？
  这个注册服务要下载disco那个项目吧
7.路由服务在哪儿？端口号多少？

**Comment by tonyboxes** [comment]
是不是没使用go mod，看着好像读了vendor？

**Comment by tonyboxes** [comment]
这个问题应该是没有打开go module，太久没回复先进行关闭了
