### ISSUE TITLE
log.go调用prometheus 出现panic

### ISSUE THREAD

**Issue by xiak** [bilibili/kratos#260]
main branch 和 0.21运行不起来 回退回020就可以

panic: descriptor Desc{fqName: "business_count_log_error_total", help: "", constLabels: {}, variableLabels: [source]} is invalid: empty help string

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000047880, 0xc00021a690, 0x1, 0x1)
        C:/Drizzt/projects/GOPATH/src/github.com/prometheus/client_golang/prometheus/registry.go:363 +0xb4
github.com/prometheus/client_golang/prometheus.MustRegister(...)
        C:/Drizzt/projects/GOPATH/src/github.com/prometheus/client_golang/prometheus/registry.go:155
github.com/bilibili/kratos/pkg/stat/metric.NewCounterVec(0xc0001e3e50, 0x1057a40, 0x1c0008)
        C:/Drizzt/projects/GOPATH/src/github.com/bilibili/kratos/pkg/stat/metric/counter.go:70 +0x192
github.com/bilibili/kratos/pkg/stat/metric.NewBusinessMetricCount(0xafd43e, 0xf, 0xc00021a660, 0x1, 0x1, 0x0, 0x0)
        C:/Drizzt/projects/GOPATH/src/github.com/bilibili/kratos/pkg/stat/metric/metric.go:60 +0x100
github.com/bilibili/kratos/pkg/log.init.ializers()
        C:/Drizzt/projects/GOPATH/src/github.com/bilibili/kratos/pkg/log/log.go:49 +0x179

**Comment by tonyboxes** [comment]
prometheus client是那个版本的呢，可以帮定位一下，然后加上对应的help试试？

![image](https://user-images.githubusercontent.com/3871120/62843535-0c3b6180-bced-11e9-82ed-c4ee35fa7052.png)

**Comment by tonyboxes** [comment]
@xiak 好像看错误没用到go mod，直接使用了本地gopath版本

**Comment by tonyboxes** [comment]
这个问题应该是没打开go module，太久没回复先关闭了

**Comment by tonyboxes** [comment]
这个问题应该是没打开go module，太久没回复先关闭了
