### ISSUE TITLE
报了一个panic: kratos new login --proto

### ISSUE THREAD

**Issue by wakaryry** [bilibili/kratos#263]
```
kratos new login --proto
panic: exec: "kratos": executable file not found in $PATH

goroutine 1 [running]:
main.main()
	/Users/.../go/pkg/mod/github.com/bilibili/kratos@v0.2.1/tool/kratos/main.go:82 +0x8fa
```

**Comment by wakaryry** [comment]
结构如图：
![image](https://user-images.githubusercontent.com/7576559/62934374-fb771280-bdf6-11e9-93ed-bae5d6c82c64.png)

准备用kratos练手一个项目，这样组织service可不可以（放到一个目录下）。

**Comment by tonyboxes** [comment]
`go env` 可以发一下份看看，会不会gobin和gopath的问题

**Comment by wakaryry** [comment]
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wakaryredou/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wakaryredou/go"
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wakaryredou/GitHub/server/friends/login/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t9/s62h_sys0nj3gc0rmr3kgylc0000gn/T/go-build912811069=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by wakaryry** [comment]
```
wakarydeMacBook-Pro:friends wakaryredou$ kratos new test --proto
go get -u github.com/bilibili/kratos/tool/kratos-protoc
运行 protoc 出错: chdir bin: no such file or directory
运行 protoc 出错: fork/exec bin/kratos-protoc: no such file or directory
Project: test
Owner: 
Module Name: test
WithGRPC: true
Directory: /Users/wakaryredou/GitHub/server/friends/test
```

**Comment by tonyboxes** [comment]
可以先手动安装试试：`go get -u github.com/bilibili/kratos/tool/kratos-protoc`

应该跟issues #264 类似

**Comment by tonyboxes** [comment]
@wakaryry 是不是没安装protobuf的？

**Comment by tonyboxes** [comment]
这个重复了
