### ISSUE TITLE
kratos tool install 需要在GOPATH目录下操作

### ISSUE THREAD

**Issue by wakaryry** [bilibili/kratos#264]
```
/Users/wakary/go/bin/kratos tool
genbts(未安装): 缓存回源逻辑代码生成器 Author(kratos) [2019/07/23]
genmc(未安装): mc缓存代码生成 Author(kratos) [2019/07/23]
kratos(未安装): Kratos工具集本体 Author(kratos) [2019/06/21]
protoc(未安装): 快速方便生成pb.go的protoc封装，windows、Linux请先安装protoc工具 Author(kratos) [2019/06/21]
swagger(未安装): swagger api文档 Author(goswagger.io) [2019/05/05]

安装工具: kratos tool install demo
执行工具: kratos tool demo
安装全部工具: kratos tool install all

详细文档： https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/kratos-tool.md
/Users/wakary/go/bin/kratos tool install protoc
go get -u github.com/bilibili/kratos/tool/kratos-protoc
运行 protoc 出错: chdir bin: no such file or directory
```

需要在GOPATH目录下操作才能成功。希望文档里面加一个提示。

**Comment by tonyboxes** [comment]
本地是不是配置了GOBIN或者多个GOPATH的？

**Comment by wakaryry** [comment]
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GO111MODULE=on
export GOPROXY=https://mirrors.aliyun.com/goproxy/

**Comment by wakaryry** [comment]
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wakaryredou/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/wakaryredou/go"
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wakaryredou/GitHub/server/friends/login/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t9/s62h_sys0nj3gc0rmr3kgylc0000gn/T/go-build912811069=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by tonyboxes** [comment]
看起来环境应该也没问题，其实安装时也只是执行了go get，理论上应该都可以的，可能是这几个参数在windows下面有点问题，可以帮忙调试一下不啊？
![image](https://user-images.githubusercontent.com/3871120/63067811-4d2cb380-bf43-11e9-9154-b7242867c29b.png)

**Comment by wakaryry** [comment]
看看这是不是想要的。不过我这是Mac本。前面所有的操作都是在这一个本上进行的。

```
package main

import (
	"fmt"
	"os/exec"
	"path/filepath"
)

func test(cmd string) {
	fmt.Printf("cmd: %s \n", cmd)
	if filepath.Base(cmd) == cmd {
		lp, err := exec.LookPath(cmd)
		if err != nil {
			fmt.Printf("error(%v) \n", err)
			return
		}
		fmt.Printf("LookPath: (%s) \n", lp)
	} else {
		fmt.Printf("Base: %s \n", filepath.Base(cmd))
	}
}

func main() {
	const cmd string = "kratos tool install genmc"
	// const cmd string = "/Users/wakaryredou/go/bin/kratos tool install genmc"
	test(cmd)
}

// Run go
/*
wakarydeMacBook-Pro:playgo wakaryredou$ go run *.go
cmd: /Users/wakaryredou/go/bin/kratos tool install genmc
Base: kratos tool install genmc

wakarydeMacBook-Pro:playgo wakaryredou$ go run *.go
cmd: kratos tool install genmc
error(exec: "kratos tool install genmc": executable file not found in $PATH)
wakarydeMacBook-Pro:playgo wakaryredou$
*/


// In Mac cmd
/*
wakarydeMacBook-Pro:~ wakaryredou$ cd
wakarydeMacBook-Pro:~ wakaryredou$ kratos tool install genmc
go get -u github.com/bilibili/kratos/tool/kratos-gen-mc
运行 genmc 出错: chdir bin: no such file or directory
wakarydeMacBook-Pro:~ wakaryredou$
*/

```

**Comment by tonyboxes** [comment]
PATH里面有没有进行配置$GOPATH/bin的，例如：

export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

**Comment by wakaryry** [comment]
`.bash_profile`里面设置了：

```
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GO111MODULE=on
export GOPROXY=https://mirrors.aliyun.com/goproxy/

export GOPATH_BIN=$HOME/go/bin
export PATH=$PATH:$GOPATH_BIN

```
我过段时间再重试次看看吧。

**Comment by tonyboxes** [comment]
@wakaryry 是不是没安装protobuf的？

**Comment by wakaryry** [comment]
安装了的。我的protoc指令是可以用的。

**Comment by tonyboxes** [comment]
有找到具体问题不呢，protoc应该需要3.6.x以上的版本

**Comment by wakaryry** [comment]
```
protoc --version
libprotoc 3.7.1
```
![image](https://user-images.githubusercontent.com/7576559/63688428-ef994080-c839-11e9-8406-a4b13de50c87.png)

我硬是没有找到啥原因。不过也不影响开发，可以直接使用protoc。

**Comment by tonyboxes** [comment]
应该是没配置gopath，然后读的gobin目录引起的

#297
