### ISSUE TITLE
dao struct方法在service中调用的迷惑

### ISSUE THREAD

**Issue by wakaryry** [bilibili/kratos#268]
**新手问题：**
在 `dao package` 下，`Dao`是`interface`，`dao struct`是对外不可见的。`service package`与`dao package`是平行的，在`service package`中，我要怎么样调用`dao struct`的方法。

我现在想的是：我是不是需要把所有的 `dao struct`的方法添加进入`Dao interface`里面？但是这样做的话，感觉直接去掉`Dao interface`，将`dao struct`对外开放更清晰。

## 同一个package下：
```go
package main

import "fmt"

type Dao interface {
    Close()
    Ping()
}

type dao struct {
    db string
}


func NewDao() Dao {
    return &dao{
        db: "MySQLDB",
    }
}


func (d *dao)Close() {
    //
}

func (d *dao)Ping() {
    //
}

func (d *dao)SayDBName() {
    fmt.Printf("My used database is %s", d.db)
}

type Service struct {
    dao Dao
}

func NewService() *Service {
    return &Service{
        dao: NewDao(),
    }
}

func (s *Service)Close() {
    //
}

func (s *Service)Ping() {
    //
}

func (s *Service)CallSayDBName() {
    s.dao.(*dao).SayDBName()
}

func main() {
    s := NewService()
    s.CallSayDBName()
}
```

### dao
```go
package dao

import "fmt"

type Dao interface {
	Close()
	Ping()
}

type dao struct {
	db string
}


func NewDao() Dao {
	return &dao{
		db: "MySQLDB",
	}
}


func (d *dao)Close() {
	//
}

func (d *dao)Ping() {
	//
}

func (d *dao)SayDBName() {
	fmt.Printf("My used database is %s", d.db)
}

```
### service
```go
package service

import "playgo/dao"

type Service struct {
	dao dao.Dao
}

func NewService() *Service {
	return &Service{
		dao: dao.NewDao(),
	}
}

func (s *Service)Close() {
	//
}

func (s *Service)Ping() {
	//
}

func (s *Service)CallSayDBName() {
	// how could I call the SayDBName method?
}
```

谢谢🙏

**Comment by tonyboxes** [comment]
`dao interface`，是为了提供外部使用的方法，也方便单元测试进行mock的

**Comment by wakaryry** [comment]
好的。明白了。那我把 对外要调用的/测试的 方法也加进 `Dao interface` 里面。

**Comment by wakaryry** [comment]
@tonyboxes 
另外我想请教一下：
我现在有一个`friends`项目，`friends`项目下面有`account`，`login`服务，他们都分别有自己的`go.mod`，`account`，`login`服务都是在`friends`根目录下。

现在我想搞一个公共的库`common`，`account`和`login`这些服务都能够从公共库（`common`）里面`import`内容。

我是这样处理的，不知道是不是正规的方式。

我建立了一个`common`服务，也有自己的`go.mod`，`go.mod`里面`module`叫做 `friends/common`。

然后我在`account`的`go.mod`中把 `friends/common v0.0.0` 加入了 `require`里面。在`require`的上面加了一条`replace`，指向本地代码地址：

> replace friends/common => /Users/wakaryredou/GitHub/server/friends/common

在`account`中需要引入`common`的文件中: `import friends/common/xxx` 。

发现可以正常使用。

就是不知道这个是不是就是正规操作。

麻烦指点一下。谢谢。

**Comment by tonyboxes** [comment]
嗯，这样子是可以的，其实需要看构建发布系统怎么方便，也就两种方式：单个go.mod和多个go.mod的

**Comment by wakaryry** [comment]
好的。谢谢。
