### ISSUE TITLE
关于ecode的用法

### ISSUE THREAD

**Issue by Colstuwjx** [bilibili/kratos#278]
如题，ecode用法暂时缺乏文档，目前我这边看下来觉得用法就是单独维护一个error包，然后在这个error包里注册一系列的ecode，比如校验错误，序列化错误等，但是有个问题：错误传递过程中怎么处理？比如如下代码：
```
func doSth(ctx *bm.Context) {
    ...
    _, err := callOtherFuncDoSth(ctx)
    if err != nil {
        // 这里该怎么写呢？如果写err的话返回就不是ecode对象，bm会当成500处理
       // 如果把callOtherFuncDoSth返回值改成返回ecode对象的话，那改动就很多了，是否有必要呢？而且ecode对象的错误信息是固定的，初始化时便通过`ecode.Register`注册到map里，那么用户得到的错误信息便不是具体这次请求的错误返回信息了，比如我是一次表单的提交，那么只能看到“表单字段校验有误”之类的信息，但是用户其实想看到的是“姓名字段不能为空”这样的信息。
        ctx.JSON(nil, err)
        return
    }
}
```
希望能补充一下相关的文档和最佳实践，谢谢！

**Comment by Colstuwjx** [comment]
@tony @felixhao  跪求大佬们帮忙解答一下

**Comment by Terry-Mao** [comment]
好问题，这块确实文档化不够。

建议如下：

如果是明确的业务错误，可以再你的某个微服务项目里定义好的ecode，直接返回比如
ecode.XXX，如果是动态的错误，也可以用ecode.Error

**Comment by LibiChai** [comment]
kratos里的ecode除了默认定义的十几个，其他你可以理解为自定义的业务层面的错误码。
比如可以使用 `var ImageTooBig = ecode.New(300001)`  来定义一个图片过大的错误。
在业务逻辑内遇到处理图片过大时 返回这个err 。最终响应结果就是 http状态码为200  响应体内的code为 300001；
当返回一个非ecode的error时，默认视为服务器内部错误 返回503错误。 
所以按照执行预期来使用ecode就可以。比如mysql执行失败这种预期外的错误就应该返回503；用户提交了错误的用户名和密码这种应该时预期内的返回自定义的业务层的ecode error。

**Comment by Terry-Mao** [comment]
@LibiChai @Colstuwjx 

我们会尽快出一份完整的wiki，关于内部系统错误，以及业务错误分别怎么处理，相应的错误的文本，应该怎么变更加载。以及服务和服务之间如何处理错误，可以统一在 #387 讨论
