### ISSUE TITLE
paladin 增加返回 confPath 的方法

### ISSUE THREAD

**Issue by sandacn** [bilibili/kratos#284]
我这里有一个需求是，一些文件也是和环境有关系，我就放到了对应的配置目录下了，比如 configs/dev/xxxx/abc
对应的配置我会写 
abc.toml
```toml
File="xxxx/abc"
```
File 用的是相对路径来处理的，根据当前的配置目录而变化的。

启动服务的时候， 传入 main -conf=configs/dev/
但是 paladin 不支持读取配置文件目录的方法，导致我必须用一些特别猥琐的方法：
```go
confVal := flag.Lookup("conf")  
```
我希望在 paladin 的default.go 中有一个方法，可以直接暴露出
```go
var (
	// DefaultClient default client.
	DefaultClient Client
	confPath      string
)

```

中的 confPath 变量，这样可以根据这个做一些处理，而不是我用 flag 再去 lookup ...

如果可以的话，我可以帮忙加这个方法

**Comment by tonyboxes** [comment]
类似这个情况，应该有多份配置，例如：
configs
-prod
-develop

运行时指定 -conf=configs/develop 应该就可以了；
paladin内置可以获取对应的config name得到内容；
应该用不到config path？

**Comment by sandacn** [comment]
你没明白我的意思，我现在就是用conf=configs/dev 来处理的，但是其他的配置文件中会用相对配置文件的相对路径来读取对应的文件，所以有一个相对路径转完整路径的过程，如果没有配置文件的目录，是没有办法转为完整路径，也就没有办法读取

**Comment by sandacn** [comment]
举个例子吧，配置文件里面写了一个配置是：
dbPath="./abc.db"

这个时候程序能读取到 dbPath, 但是是相对路径，这个时候得转为完整路径，对应的api才能读取到 dbPath 下的文件

**Comment by tonyboxes** [comment]
配置其实应该直接获取到内容，假如：resource = /tmp/data.bin，如果配置里面出现文件路径，应该是以绝对路径进行读取，不建议通过相对路径，并且是自己已知的，不然都应该使用配置paladin.Get方式获取。
