### ISSUE TITLE
kratos new kratos-demo无法执行

### ISSUE THREAD

**Issue by muzzylion** [bilibili/kratos#294]
求助啊……
ubuntu1904
前提Go version>=1.12 and GO111MODULE=on已确认
执行kratos new kratos-demo失败。
报kratos: command not found，求指导～

**Comment by orca-zhang** [comment]
kratos安装了不

先看一下$GOPATH/bin/目录下有没有，如果有的话，确认一下bin目录有没有添加到$PATH

**Comment by tonyboxes** [comment]
应该是没配置gopath，然后读的gobin目录引起的

#297

**Comment by wnz27** [comment]
> 应该是没配置gopath，然后读的gobin目录引起的
> 
> #297

$GOPATH/bin 含有kratos, cd进去也运行不了

**Comment by Song2017** [comment]
```
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
```
