### ISSUE TITLE
go get -u github.com/bilibili/kratos/tool/kratos 报错

### ISSUE THREAD

**Issue by gstormlee** [bilibili/kratos#299]
go get: upgrading golang.org/x/time@v0.0.0-20190513212739-9d24e82272b4: unrecognized import path "golang.org/x/time" (https fetch: Get https://golang.org/x/time?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/crypto@v0.0.0-20190701094942-4def268fd1a4: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/prometheus/procfs v0.0.4
go get: upgrading golang.org/x/sys@v0.0.0-20180909124046-d0be0721c37e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sys@v0.0.0-20190712062909-fae7ac547cb7: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/net@v0.0.0-20190311183353-d8887717615a: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/net@v0.0.0-20190628185345-da137c7871d7: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sys@v0.0.0-20190422165155-953cdadca894: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding gopkg.in/tomb.v1 latest
go get: upgrading google.golang.org/grpc@v1.20.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/sys@v0.0.0-20180830151530-49385e6e1522: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding go.etcd.io/etcd v0.0.0-20190720005121-fe86a786a4c3
go get: upgrading google.golang.org/appengine@v1.1.0: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading google.golang.org/appengine@v1.6.1: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go get: upgrading golang.org/x/net@v0.0.0-20181220203305-927f97764cc3: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/golang/glog latest
go get: upgrading golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding gopkg.in/check.v1 latest

上面是错误的一部分，请问该问题如何解决

**Comment by fujiajun** [comment]
设置下 GOPROXY = https://goproxy.io  再试试

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/FAQ.md

可以按这个试试

**Comment by gstormlee** [comment]
thanks
