### ISSUE TITLE
kratos new xxx --proto 报错

### ISSUE THREAD

**Issue by limhu** [bilibili/kratos#303]
执行 `go get -u github.com/bilibili/kratos/tool/kratos-protoc` 有个依赖无法下载

![image](https://user-images.githubusercontent.com/17063861/63760701-685bd380-c8f2-11e9-80b7-c00efd04f45a.png)

![image](https://user-images.githubusercontent.com/17063861/63760752-81648480-c8f2-11e9-8688-19f2fc5b7847.png)

**Comment by limhu** [comment]
换了阿里的代理也是一样

**Comment by tonyboxes** [comment]
因为gopath没配置时使用失败了，master已经修复这个问题

**Comment by tonyboxes** [comment]
@limhu 这个可以尝试清理go mod cache试试

**Comment by Mephostopilis** [comment]
还是有这个问题。怎么解决，gopath我是配置了的

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/FAQ.md

@Mephostopilis 应该go mod缓存版本串了，需要清理一下 `go clean --modcache`

**Comment by tonyboxes** [comment]
详细查看 #304
