### ISSUE TITLE
go get -u github.com/bilibili/kratos/tool/kratos error

### ISSUE THREAD

**Issue by gstormlee** [bilibili/kratos#304]
执行上述操作时出现：
go: gopkg.in/jcmturner/rpc.v1@v1.1.1: parsing go.mod: missing module line
go get: error loading module requirements

我的go version
go version go1.12.5 darwin/amd64

这个是什么问题？

**Comment by Mephostopilis** [comment]
同一个问题

**Comment by gstormlee** [comment]
不明白？我设置了proxy，上次的问题不再出现却出现这个问题，也就是说我设置了proxy， 然后出了这个问题。我该怎么做？

**Comment by tonyboxes** [comment]
这个应该是kafka sarama 依赖的pkg，我们看看能不能升级一下

**Comment by tonyboxes** [comment]
```
cd $GOPATH/pkg/mod/
grep -R jcmturner .
```
好像没看到有依赖这个库，帮grep看看是那里依赖了的；
也可以尝试：`rm -rf $GOPATH/pkg/mod/cache`，再进行`go build`。

**Comment by Teddy2014** [comment]
> ```
> cd $GOPATH/pkg/mod/
> grep -R jcmturner .
> ```
> 
> 好像没看到有依赖这个库，帮grep看看是那里依赖了的；
> 也可以尝试：`rm -rf $GOPATH/pkg/mod/cache`，再进行`go build`。

![image](https://user-images.githubusercontent.com/6234367/64140101-d560f300-ce35-11e9-97a2-0333136fa83a.png)
我这里是这样的

**Comment by tonyboxes** [comment]
@Teddy2014 go mod 其实没依赖这个库的？我看了kratos几个版本好像都没用到kafka lib

**Comment by tonyboxes** [comment]
这个错误应该是kafka sarama依赖了已经删除的版本，需要更新或者replace下，帮本地试试能不能解决

**Comment by tonyboxes** [comment]
是zipkin依赖了sarama，我更新下version

**Comment by tonyboxes** [comment]
@Teddy2014 你的本地cache也存在问题，现在sarama v1.23.1依赖了 gopkg.in/jcmturner/rpc.v1@v1.1.0版本的，需要rm -rf mod/cache

**Comment by Teddy2014** [comment]
> @Teddy2014 你的本地cache也存在问题，现在sarama v1.23.1依赖了 gopkg.in/jcmturner/rpc.v1@v1.1.0版本的，需要rm -rf mod/cache

现在已经ok了。我昨天手动改了cache中jcmturner的mod才可以用。
