### ISSUE TITLE
外部调用该如何加入context

### ISSUE THREAD

**Issue by Colstuwjx** [bilibili/kratos#315]
如题，如果使用kratos的bm编写了一个http服务，该服务A调用了另外一个服务B并获取返回数据，然后加工处理下返回到用户的话，这个该怎么把context上下文传递下去？想消费kratos现有提供的一些比如超时配额等功能。

谢谢！

**Comment by Terry-Mao** [comment]
是说 怎么去读取这些 context 跨服务传递的数据解析么？

**Comment by Colstuwjx** [comment]
举个例子，比如DB的操作目前kratos是自行在官方的sql库基础上做了一个封装，用户传入的context，会被逐层传递，然后做一些处理，比如trace、比如超时处理，比如Query实际上是调用了[这里](https://github.com/bilibili/kratos/blob/master/pkg/database/sql/sql.go#L380)的方法：
```
func (db *conn) query(c context.Context, query string, args ...interface{}) (rows *Rows, err error) {
        ...
	if t, ok := trace.FromContext(c); ok {
		t = t.Fork(_family, "query")
		t.SetTag(trace.String(trace.TagAddress, db.addr), trace.String(trace.TagComment, query))
		defer t.Finish(&err)
	}
        ...
	_, c, cancel := db.conf.QueryTimeout.Shrink(c)
	rs, err := db.DB.QueryContext(c, query, args...)
}
```
上述这个`query`方法在接收到context和查询参数后封装了具体的超时时间计算，trace的tag设置等。

那么，其他服务是否也要类似地这样封装才能消费到kratos基于context提供的trace和timeout quota等特性呢？有没有啥方便或者推荐的写法？比如调用一个内部的消息队列服务或者调用一个其他的基础服务如账号服务获取用户信息。

**Comment by Terry-Mao** [comment]
一般建议是一劳永逸的做法，把你需要的第三方库引入，然后修改。
当然如果第三方库扩展的比较友好，那么你可以通过他的Inteceptor等方式来修改，否则确实没什么好办法，所以一般做法是构建自己的基础库，把常用的feature做进去。
