### ISSUE TITLE
端口2333冲突

### ISSUE THREAD

**Issue by dalaoting** [bilibili/kratos#318]
kratos bm服务和discovery同时用到blademaster依赖，本地调试时无法同时启动，请问这个2333端口监听是作用于什么，以上描述的问题要怎么解决

**Comment by coder-zhuyu** [comment]
2333端口是以前的默认perf监听端口，最新代码已经改成默认和应用使用同一个端口了，你可以更新到最新的仓库代码，具体代码文件kratos/pkg/net/http/blademaster/perf.go

**Comment by tonyboxes** [comment]
可以使用最新master，或者等新版本就可以perf和http端口共存了

**Comment by dalaoting** [comment]
好的，谢谢
