### ISSUE TITLE
demo 执行指令 go build 的时候 提示has unexpected file github.com/prometheus/client_model@v0.0.0-20190129233127-fd36f4220a90/.gitignore

### ISSUE THREAD

**Issue by lifengjacky** [bilibili/kratos#320]
go: downloading github.com/prometheus/client_model v0.0.0-20190220174349-fd36f4220a90
build kratos-demo/cmd: cannot load github.com/prometheus/client_model/go: zip for github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90 has unexpected file github.com/prometheus/client_model@v0.0.0-20190129233127-fd36f4220a90/.gitignore

**Comment by C-isCoder** [comment]
go env 代理的问题，看一下 FAQ.md 文档

**Comment by tonyboxes** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/FAQ.md

可以按文档更换goproxy或者`go clean --modcache`清理缓存试试
