### ISSUE TITLE
不能 get 到  kratos tool

### ISSUE THREAD

**Issue by ryanwx** [bilibili/kratos#331]
运用了多种  GOPROXY ，都不能成功  go get ，建议可以测试下，没有能成功的，不使用  GOPROXY 也不能正常 get 到，实在是无比难受。

**Comment by dalaoting** [comment]
查看下你go env的配置信息，还有gomod配置是否正确

**Comment by ryanwx** [comment]
> 查看下你go env的配置信息，还有gomod配置是否正确

都看了，确定是有问题的

**Comment by ryanwx** [comment]
![image](https://user-images.githubusercontent.com/52447036/64762161-35f7da80-d570-11e9-97fa-06acef905fd5.png)

即使不适用 goproxy ,使用自用的 科学上网代理，依然是不行的

**Comment by SongChen870909** [comment]
同样的问题
“verifying github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c: 404 Not Found”
设置的goproxy = https://goproxy.cn

**Comment by C-isCoder** [comment]
> 同样的问题
> “verifying github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: reading https://goproxy.cn/sumdb/sum.golang.org/lookup/github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c: 404 Not Found”
> 设置的goproxy = https://goproxy.cn

换个代理，清理 mod 缓存试试，可以试试阿里云的代理

**Comment by fengdays** [comment]
bash: kratos: command not found

**Comment by Terry-Mao** [comment]
已经修复

**Comment by FlyingKirito** [comment]
请问楼主解决了么 我这边也是一样所以代理是一遍只有https://goproxy.cn这个代理都问题最少 还是有一条gopkg.in/jcmturner/rpc.v1 的404

**Comment by ruinshe** [comment]
我这边一样遇到bigfft包下不下来的问题，用的proxy是`https://goproxy.cn,direct`

`go env`的结果：

```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ruinshe/.cache/go-build"
GOENV="/home/ruinshe/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ruinshe/.go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/srv/go/src/ruinshe/kratos-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build129332093=/tmp/go-build -gno-record-gcc-switches"
```
