### ISSUE TITLE
go get -u github.com/bilibili/kratos/tool/kratos 安装错误

### ISSUE THREAD

**Issue by jayn1985** [bilibili/kratos#343]
提示找不到下面的包（看了下下载的tag是0.2.2版本）：
go: github.com/spf13/pflag@v1.0.4: parsing go.mod: unexpected module path "github.com/spf13/pflags"

ps: 试了下 go get -u github.com/bilibili/kratos/tool/kratos@master也是同样的问题

**Comment by jayn1985** [comment]
pps：把Issues列表浏览了下，看到了不少反映安装的问题，然后刚才试了一把：
go get -u github.com/bilibili/kratos/tool/kratos@v0.2.0

但是提示：
go: gopkg.in/jcmturner/rpc.v1@v1.1.1: parsing go.mod: missing module line

然后又显式的在项目go.mod里面：
replace gopkg.in/jcmturner/rpc.v1 v1.1.1 => gopkg.in/jcmturner/rpc.v1 v1.1.0

才正常。。。
希望能解决下最新版本的包依赖问题

**Comment by aston-x** [comment]
同上
