### ISSUE TITLE
/src/github.com/bilibili/kratos/third_party: warning: directory does not exist.

### ISSUE THREAD

**Issue by Zenger-sun** [bilibili/kratos#344]
首先，golang大法好！^_^
你好，最近接触到kratos，个人认为是一个完成度很高的后端服务框架，正在努力学习ing。
由于我开发的环境是windows，在安装kratos并使用protobuf的时候遇到一些问题，主要就是标题所示。
后来到github.com\bilibili\kratos\tool\kratos-protoc\protoc.go中看到
func gopath() (gp string) {
	gopaths := strings.Split(os.Getenv("GOPATH"), ":")
用了冒号分割gopath，而windows中用的是分号，我改成分号后能成功创建了，，
我在issues中没有找到想要的答案，所以建了一个issues，希望官方能够兼容一下。

**Comment by Terry-Mao** [comment]
可以贡献一个pr么

**Comment by Zenger-sun** [comment]
> 可以贡献一个pr么

感谢您的邀请，我已经提交了一个pr，有不对的地方请向我指出^_^

**Comment by XyuWang** [comment]
https://github.com/bilibili/kratos/pull/349 已合并
