### ISSUE TITLE
kratos-demo打开出错,Windows,Goland...怎么解决呢?

### ISSUE THREAD

**Issue by dmqm** [bilibili/kratos#351]
verifying github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: github.com/remyoudompheng/bigfft@v0.0.0-20190806203942-babf20351dd7e3ac320adedbbe5eb311aec8763c/go.mod: malformed record data
![图片](https://user-images.githubusercontent.com/19336959/65380877-aa244200-dd17-11e9-9ea2-df484c4107d4.png)

**Comment by XyuWang** [comment]
最新的master分支还有这个问题吗

**Comment by dmqm** [comment]
昨天刚拉的

**Comment by XyuWang** [comment]
试了一下 windows  + goland + go1.13 一切正常 没复现这个问题
