### ISSUE TITLE
demo go build fail

### ISSUE THREAD

**Issue by mouuii** [bilibili/kratos#353]
最新demo不行啊，起不来

verifying github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90/go.mod: github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90/go.mod: reading https://sum.golang.org/lookup/github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: 410 Gone

**Comment by XyuWang** [comment]
设置GOSUMDB=off 有效吗

**Comment by XyuWang** [comment]
kratos new 生成的吗  请用最新master重试一下

**Comment by XyuWang** [comment]
https://github.com/bilibili/kratos/pull/354
