### ISSUE TITLE
gopkg.in/jcmturner/rpc.v1@v1.1.1 依赖报错

### ISSUE THREAD

**Issue by lvxj** [bilibili/kratos#357]
我看其他人提的issues有相关这个问题，但是我没有解决，
我用了goproxy在https://goproxy.io与https://mirrors.aliyun.com/goproxy/，甚至direct之间切换，都不行

最开始我安装
go get -u github.com/bilibili/kratos/tool/kratos会提示，然后我在mod中添加：
replace gopkg.in/jcmturner/rpc.v1 v1.1.1 => gopkg.in/jcmturner/rpc.v1 v1.1.0
就可以了，然后创建项目：
kratos new kratos-demo 简单跑了跑没什么问题

但是，当我运行 kratos new kratos-demo2  --proto时候，铛铛铛～～这歌报错又来了，

报错信息如下：
go: gopkg.in/jcmturner/rpc.v1@v1.1.1: unexpected status (https://goproxy.io/gopkg.in/jcmturner/rpc.v1/@v/v1.1.1.mod): 404 Not Found
go: finding github.com/dgryski/go-sip13 latest
go: finding gopkg.in/bsm/ratelimit.v1 latest
go get: error loading module requirements
运行 protoc 出错: fork/exec /Users/seven/Developer/gopath/bin/kratos-protoc: no such file or directory

我看了其他issue，你让cd $GOPATH/pkg/mod，然后grep  -R jcmturner . ,输出：
./cache/download/github.com/!shopify/sarama/@v/v1.23.1.mod:     github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
./cache/download/github.com/!shopify/sarama/@v/v1.23.1.mod:     gopkg.in/jcmturner/aescts.v1 v1.0.1 // indirect
./cache/download/github.com/!shopify/sarama/@v/v1.23.1.mod:     gopkg.in/jcmturner/dnsutils.v1 v1.0.1 // indirect
./cache/download/github.com/!shopify/sarama/@v/v1.23.1.mod:     gopkg.in/jcmturner/gokrb5.v7 v7.2.3
./cache/download/github.com/!shopify/sarama/@v/v1.23.1.mod:     gopkg.in/jcmturner/rpc.v1 v1.1.0 // indirect
./cache/download/github.com/aristanetworks/goarista/@v/v0.0.0-20190912214011-b54698eaaca6.mod:  gopkg.in/jcmturner/goidentity.v3 v3.0.0 // indirect
./cache/download/github.com/aristanetworks/goarista/@v/v0.0.0-20190924011532-60b7b74727fd.mod:  gopkg.in/jcmturner/goidentity.v3 v3.0.0 // indirect
./cache/download/github.com/jcmturner/gofork/@v/v0.0.0-20190328161633-dc7c13fece03.mod:module github.com/jcmturner/gofork
./cache/download/github.com/jcmturner/gofork/@v/v1.0.0.mod:module github.com/jcmturner/gofork
./cache/download/gopkg.in/jcmturner/aescts.v1/@v/v1.0.1.mod:module gopkg.in/jcmturner/aescts.v1
./cache/download/gopkg.in/jcmturner/dnsutils.v1/@v/v1.0.1.mod:module gopkg.in/jcmturner/dnsutils.v1
./cache/download/gopkg.in/jcmturner/goidentity.v3/@v/v3.0.0.mod:module gopkg.in/jcmturner/goidentity.v3
./cache/download/gopkg.in/jcmturner/gokrb5.v7/@v/v7.2.3.mod:module gopkg.in/jcmturner/gokrb5.v7
./cache/download/gopkg.in/jcmturner/gokrb5.v7/@v/v7.3.0.mod:module gopkg.in/jcmturner/gokrb5.v7
./cache/download/gopkg.in/jcmturner/rpc.v1/@v/v1.1.0.mod:module gopkg.in/jcmturner/rpc.v1
./gopkg.in/jcmturner/rpc.v1@v1.1.0/.travis.yml:go_import_path: gopkg.in/jcmturner/rpc.v1
./gopkg.in/jcmturner/rpc.v1@v1.1.0/examples/examples.go:import "gopkg.in/jcmturner/rpc.v1/mstypes"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/examples/examples_test.go:   "gopkg.in/jcmturner/rpc.v1/mstypes"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/examples/examples_test.go:   "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/mstypes/claims.go:   "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/mstypes/claims_test.go:      "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/mstypes/filetime_test.go:    "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/mstypes/rpc_unicode_string_test.go:  "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/mstypes/sid_test.go: "gopkg.in/jcmturner/rpc.v1/ndr"
./gopkg.in/jcmturner/rpc.v1@v1.1.0/README.md:[![GoDoc](https://godoc.org/gopkg.in/jcmturner/rpc.v1?status.svg)](https://godoc.org/gopkg.in/jcmturner/rpc.v1) [![Go Report Card](https://goreportcard.com/badge/gopkg.in/jcmturner/rpc.v1)](https://goreportcard.com/report/gopkg.in/jcmturner/rpc.v1) [![Build Status](https://travis-ci.org/jcmturner/rpc.svg?branch=master)](https://travis-ci.org/jcmtu

我看gopkg.in/jcmturner/rpc 只有1.0 没有1.1，我奇怪的是我在mod中都已经替换了，为啥
 kratos new kratos-p --proto还不行。。。

**Comment by XyuWang** [comment]
你好 请尝试 v0.2.3版本

**Comment by XyuWang** [comment]
请先执行 kratos self-upgrade  然后重新生成新项目看一下

**Comment by lvxj** [comment]
我执行  kratos self-upgrade ，也会报那个错
我刚执行 kratos self-upgrade，如下：
![3434](https://user-images.githubusercontent.com/15357575/65504378-625d1080-def9-11e9-949b-9a405caa0652.jpg)

**Comment by XyuWang** [comment]
go1.12请执行 go get github.com/bilibili/kratos/tool/kratos@master
