### ISSUE TITLE
go.mod文件错误

### ISSUE THREAD

**Issue by maooyer** [bilibili/kratos#358]
在引用 Kratos 并且使用 `goproxy.cn` 作为代理时会出现如下错误：

>go: finding github.com/prometheus/client_model v0.0.0-20190220174349-fd36f4220a90
>github.com/prometheus/client_model@v0.0.0-20190220174349-fd36f4220a90: proxy returned info for version v0.0.0-20190129233127-fd36f4220a90 instead of requested version

最终发现是0.22版本 `go.mod` 有错误，详情见这个 [issue](https://github.com/goproxy/goproxy.cn/issues/27)

**Comment by XyuWang** [comment]
master已经修复这个问题 请先使用master分支

**Comment by XyuWang** [comment]
已临时发布v0.2.3版本
