### ISSUE TITLE
关于kratos tool 根据proto生成协议文件的问题

### ISSUE THREAD

**Issue by wuhenfeike** [bilibili/kratos#367]
1，当使用kratos tool protoc --swagger --grpc --bm 的时候后面必须加上具体文件名字（api.proto）才可以生成对应的文件，如果我的工程中有很多个proto必须一个一个调用上面的命令生成需要的文件，比较麻烦，可以修改为根据目录搜索的方式搜索目录中所有proto文件生成对应的协议文件么；
2，如果工程的目录中有多个proto文件，而生成很多个swagger.json文件，这时候生成swagger文档就必须打开很多个地址才能看每个proto对应的swagger文档，是否改善工具合并为一个swagger.json。

**Comment by tonyboxes** [comment]
可以写个shell，遍历所有`.proto`文件，然后逐个生成就可以了

**Comment by Terry-Mao** [comment]
@tonyboxes 我们是否支持下整合多个pb单个目录下

**Comment by tonyboxes** [comment]
多个pb可以的，把 *.proto 指定下就可以生成了

**Comment by wuhenfeike** [comment]
@tonyboxes 我在windows 试过加*.proto ，貌似是不行的，另外多个proto文件，而生成很多个swagger.json文件，启动swagger文档服务的时候就要启动很多个服务器。

**Comment by Terry-Mao** [comment]
@wuhenfeike  已经支持
