### ISSUE TITLE
trace 怎么使用 Redis/Memcached 作为载体？

### ISSUE THREAD

**Issue by polyrabbit** [bilibili/kratos#371]
Hi,

文档中提到：
> Trace：基于opentracing，集成了全链路trace支持（gRPC/HTTP/MySQL/Redis/Memcached）

看起来`trace`可以将`gRPC/HTTP`作为载体，把当前上下文传递给下游调用方。但不知道后面提到的`MySQL/Redis/Memcached`也是作为载体用的？即A将数据存入后，B来取，同时B能拿到之前A的`trace`信息。

或者这里面的`gRPC/HTTP`和`MySQL/Redis/Memcached`其实并不应该放在一起？

**Comment by Terry-Mao** [comment]
因为redis/mysql只存在 client测的传递，所以是在对应client库里集成了trace获取，而需要跨服务chuandi的才存在carrier

**Comment by polyrabbit** [comment]
所以说`gRPC/HTTP`算是carrier类的，而`MySQL/Redis/Memcached`算是一种被统计的对象？

**Comment by Terry-Mao** [comment]
@polyrabbit 是的，属于component，而rpc/http属于carrier。
