### ISSUE TITLE
最新的kratos tool工具版本有误

### ISSUE THREAD

**Issue by chenquan** [bilibili/kratos#388]
![image](https://user-images.githubusercontent.com/20548053/67113434-15c0d880-f20c-11e9-9759-ab1ee5ba23ed.png)

https://github.com/bilibili/kratos/blob/9ee925668ec9ff7d5f3e0d5a3374f90cb6528418/tool/kratos/version.go#L11-L13

**Comment by chenquan** [comment]
下载master分支源码直接覆盖代码`C:\Users\${user}\go\pkg\mod\github.com\bilibili\kratos@v0.2.3`解决

**Comment by Terry-Mao** [comment]
方便PR一下？

**Comment by chenquan** [comment]
> 方便PR一下？

没办法PR吧？重新用master的版本tag一下，然后强行覆盖原来的tag。
以下为一个不错的解决方案，供参考。
```shell
git clone git@github.com:bilibili/kratos.git
cd kratos
git tag -f v0.2.3
git push origin -f --tags
```

**Comment by Terry-Mao** [comment]
这个确实，之前忘记修改版本了。我们内部讨论下后面怎么规避
