### ISSUE TITLE
windows err

### ISSUE THREAD

**Issue by gie777** [bilibili/kratos#39]
`cd cmd / go build main.go
`..\internal\service\service.go:34:54: undefined: api.HelloReq
```
cd ../api
go generate
```

> 运行 kprotoc 出错: exec: "bash": executable file not found in %PATH%
> 运行 kprotoc 出错: exec: "d:\\www\\bin\\kprotoc": file does not exist

打开D:\www\src\github.com\bilibili\kratos\tool\kprotoc
` ./install_kprotoc.sh
`ln: failed to create symbolic link 'd/bin/kprotoc': No such file or directory

**Comment by gie777** [comment]
```
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\www\
set GOPROXY=
set GORACE=
set GOROOT=D:\Go
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build466831162=/tmp/go-build -gno-record-gcc-switche
```

**Comment by gie777** [comment]
还有,在MINGW64 用命令报错cmd下没事
$ kratos init
? 你想怎么玩？  [Use arrows to move, space to select, type to filter]
> 一键初始化项目
  自定义项目参数
panic: The handle is invalid.

goroutine 1 [running]:
main.main()
        d:/www/src/github.com/bilibili/kratos/tool/kratos/main.go:70 +0x7c7

**Comment by whtiehack** [comment]
上面这个错误是 survey对windows的支持有问题。

**Comment by felixhao** [comment]
@gie777 因为 `kprotoc`工具是一个shell脚本，所以只能在macos或Linux机器上运行，目前还没有windows bat的支持。
如果可行，建议装个linux虚拟机完成上面操作。
也可以直接从 `git clone https://github.com/bilibili/kratos-demo`的代码来进行二次修改运行。

**Comment by gie777** [comment]
> @ gie777因为`kprotoc`工具是一个shell脚本，所以只能在macos或Linux机器上运行，目前还没有windows bat的支持。
> 如果可行，建议装个linux虚拟机完成上面操作。
> 也可以直接从`git clone https://github.com/bilibili/kratos-demo`的代码来进行二次修改运行。

嗯,已经解决了,从那边复制了一个代码过来了,
