### ISSUE TITLE
idea 路径错误

### ISSUE THREAD

**Issue by wuyuancai** [bilibili/kratos#397]
在goland 构建项目，路径报错

**Comment by Terry-Mao** [comment]
能给点明细么，不然只能猜谜啊

**Comment by wuyuancai** [comment]
![image](https://user-images.githubusercontent.com/19992054/67834718-19653100-fb23-11e9-85bc-7a7a570b45b6.png)
使用kratos 工具生成的项目在idea 下import包错误，修改后项目不能运行

**Comment by wuyuancai** [comment]
> 能给点明细么，不然只能猜谜啊
![image](https://user-images.githubusercontent.com/19992054/67834718-19653100-fb23-11e9-85bc-7a7a570b45b6.png)
使用kratos 工具生成的项目在idea 下import包错误，修改后项目不能运行

**Comment by Terry-Mao** [comment]
go module 开启了么，什么版本，错误信息是什么？

**Comment by wuyuancai** [comment]
> go module 开启了么，什么版本，错误信息是什么？

go version go1.13 windows/amd64
没有错误信息，
![image](https://user-images.githubusercontent.com/19992054/68017541-ef05a600-fcd1-11e9-9d05-f31e5aa0e7db.png)
![image](https://user-images.githubusercontent.com/19992054/68017552-f331c380-fcd1-11e9-9b51-e532531b2255.png)

**Comment by wuyuancai** [comment]
> > go module 开启了么，什么版本，错误信息是什么？
> 
> go version go1.13 windows/amd64
> 没有错误信息，
> ![image](https://user-images.githubusercontent.com/19992054/68017541-ef05a600-fcd1-11e9-9d05-f31e5aa0e7db.png)
> ![image](https://user-images.githubusercontent.com/19992054/68017552-f331c380-fcd1-11e9-9b51-e532531b2255.png)

![image](https://user-images.githubusercontent.com/19992054/68017610-0fcdfb80-fcd2-11e9-9638-b837c5c226cc.png)

**Comment by tonyboxes** [comment]
本地go build 或者 go mod download可以把依赖包自动下载的

**Comment by tonyboxes** [comment]
这个应该是本地环境没配置好
