### ISSUE TITLE
http 路由不支持 /:name  参数获取?

### ISSUE THREAD

**Issue by welcome112s** [bilibili/kratos#400]
/:name  目前的路由框架不支持此参数的获取? 需要手动调用c.Params.ByName("name")

**Comment by realityone** [comment]
Hi @welcome112s ,

框架里是支持获取这种参数的，你可以直接调用 `c.Params.ByName("name")` 来获取。

**Comment by welcome112s** [comment]
@realityone  
e.GET("/demo/say_hello/:name", demoSayHelloURL)
func demoSayHelloURL(c *bm.Context) {
	p := new(HelloReq)
	if err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get("Content-Type"))); err != nil {
		return
	}
	resp, err := DemoSvc.SayHelloURL(c, p)
	c.JSON(resp, err)
}
这段代码是脚手架自动生成的,  我希望在BindWith的时候自动为这种参数赋值.      我先自己改造一下源码试试

**Comment by Terry-Mao** [comment]
@realityone 应该是要支持params的binding 支持

**Comment by realityone** [comment]
嗯，目前 binding 的逻辑中还不包含对 url 中参数的支持。

短期内可以先考虑直接通过 ctx 来获取。

**Comment by welcome112s** [comment]
en 我已经解决了

**Comment by Alax-W** [comment]
为什么不支持呢？
`// Binding
var (
	JSON          = jsonBinding{}
	XML           = xmlBinding{}
	Form          = formBinding{}
	Query         = queryBinding{}
	FormPost      = formPostBinding{}
	FormMultipart = formMultipartBinding{}
)`
