### ISSUE TITLE
google/protobuf/descriptor.proto: File not found. 

### ISSUE THREAD

**Issue by myholiday** [bilibili/kratos#405]
kratos tool protoc api.proto  用来生成api.bm.go时出错 

F:\gogogo\src\kratos-demo\api>kratos tool protoc api.proto
...
go: finding github.com/samuel/go-zookeeper latest
go: finding github.com/templexxx/cpufeat latest
go: finding github.com/google/pprof latest
protoc: 安装成功!
2019/10/31 20:05:13 protoc --proto_path=F:\beebook/src --proto_path=F:\aaa/src/github.com/bilibili/kratos/third_party --proto_path=F:\aaa\src\kratos-demo\api --bm_out=:. api.proto
google/protobuf/descriptor.proto: File not found.
...

是我的配置错了吗

**Comment by myholiday** [comment]
ubuntu下完全没问题

**Comment by tangxiangquan** [comment]
window 下有这个问题

**Comment by dingyalin** [comment]
github下载protoc-xxx-win64.zip包，提取include/google包到复制到$GOPATH下/src路径下
下载地址 https://github.com/protocolbuffers/protobuf/releases
