### ISSUE TITLE
编译cmd的时候报错“..\internal\service\service.go:34:54: undefined: api.HelloReq”

### ISSUE THREAD

**Issue by xiaohei2015** [bilibili/kratos#41]
说明：进入cmd目录运行go build的时候，报了错误“..\internal\service\service.go:34:54: undefined: api.HelloReq”，对比官方给出的kratos-demo，发现api目录下面的文件api.pb.go并没有

重现步骤：
1.  go get -u github.com/bilibili/kratos/tool/kratos
2.  kratos init，按照命令要求，依次输入项目名称，负责人，并选择有gRPC的，当前目录生成
3.  进入cmd目录执行go build

环境：
1. Win7+64位
2. Go1.12.4

**Comment by lealife** [comment]
别着急, 文档还没写清楚, 要先用工具生成api.pb.go

**Comment by Terry-Mao** [comment]
@lealife 可以先关注，我们逐渐再完善中，也谢谢反馈。其实我们并不是强依赖discovery，naming是一个抽象，可以实现zk、etcd等，但是时间原因都还没来得及实现，也欢迎贡献PR

**Comment by lealife** [comment]
期待尽快完善!! 持续关注.

**Comment by fl260919784** [comment]
一键默认生成没有这个问题，自定义生成确实复现这个问题

**Comment by felixhao** [comment]
GOOS
* macos: shoult always be successful, if not install `protoc` and `gogo protobuf`, then run:
  *  `cd kratos-demo/api`
  *  `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`
* windows: install `protoc` and `gogo protobuf`，then run:
  *  `cd kratos-demo/api`
  *  `protoc --gogofast_out=plugins=grpc:$GOPATH/src api.proto`
  * `cd kratos-demo/cmd & go build`
* linux: install `protoc` first, then run:
  * `cd kratos-demo/api`
  * `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`

protoc:https://github.com/protocolbuffers/protobuf#protocol-compiler-installation
gogo protobuf:https://github.com/gogo/protobuf
kratos tool:https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/kratos-tool.md
