### ISSUE TITLE
生成swgger错误，delete方法变成了put

### ISSUE THREAD

**Issue by xu6jin** [bilibili/kratos#417]
文件：tool/protobuf/protoc-gen-bswagger/generator.go

![image](https://user-images.githubusercontent.com/48863893/68278650-c6542680-00ac-11ea-9674-4ada02eaf762.png)

**Comment by tonyboxes** [comment]
@xu6jin 帮忙提个mr修复下~

**Comment by xu6jin** [comment]
nice~
