### ISSUE TITLE
建议去掉 pkg/naming/discovery 中对 pkg/net/http/blademaster 的依赖

### ISSUE THREAD

**Issue by yuanfeng0905** [bilibili/kratos#424]
当想要在 blademaster 的 client 中实现 resolver 时，如果复用 pkg/naming 的 discovery resolver 实现，会出现循环引用问题，建议 pkg/naming/discovery 中 http client 直接使用 golang 的默认 net/http Client。

**Comment by tonyboxes** [comment]
嗯，kratos/pkg/naming打算保留这个，然后把discovery去掉了，可以直接修改为golang httpclient的。

**Comment by Terry-Mao** [comment]
应该是作为其他组件，放非 pkg目录比较合适

**Comment by Terry-Mao** [comment]
参看 #409

**Comment by yuanfeng0905** [comment]
好的，这个 issue 我关闭了。
