### ISSUE TITLE
render html

### ISSUE THREAD

**Issue by hedan806** [bilibili/kratos#43]
请问，如何支持渲染 HTML 呢？如``gin``中的``ctx.HTML()``

**Comment by Terry-Mao** [comment]
我建议合适框架做合适的事情，前端vue 加上 ssr 更合适web。kratos 纯api gateway更合适吧？

**Comment by hedan806** [comment]
感谢回答。如果是后台管理系统，上 ssr 会不会太重？因为还没接触到这一块。

**Comment by Terry-Mao** [comment]
后台系统也建议前后端分离，vue + api 就好

**Comment by yongfly** [comment]
在实际应用中，中小型项目上VUE条件不成熟时，还需要使用htmlRender。目前kratos的定位是微服务框架，但建议最好能提供c.HTML，以及相关的文件或目录Static，还有路径的:name解析等等，或者kratos能否有一个使用全功能gin的方法。
