### ISSUE TITLE
paladin 热更新失败??

### ISSUE THREAD

**Issue by huof6829** [bilibili/kratos#434]
[root@docker_hf cmd]# ./cmd -conf ../configs/
INFO 11/21-14:59:53.851 /home/gopath/pkg/mod/github.com/bilibili/kratos@v0.2.3/tool/kratos/demo/cmd/main.go:25 demo start
2019/11/21 14:59:53 paladin: start watch config: ../configs/
s=&{ac:0xc00029bfe0 dao:0xc00034db00 duration:{GameDuration:21600}}
[warden] config is Deprecated, argument will be ignored. please use -grpc flag or GRPC env to configure warden server.
INFO 11/21-14:59:53.853 /home/gopath/pkg/mod/github.com/bilibili/kratos@v0.3.2-0.20191112153429-5a8668eade4c/pkg/net/rpc/warden/server.go:329 warden: start grpc listen addr: [::]:9000
INFO 11/21-14:59:53.853 /home/gopath/pkg/mod/github.com/bilibili/kratos@v0.3.2-0.20191112153429-5a8668eade4c/pkg/net/http/blademaster/server.go:98 blademaster: start http listen addr: 0.0.0.0:8000

2019/11/21 15:00:53 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:00:53 paladin: unsupport event "../configs/.application.toml.swx": REMOVE ingored
2019/11/21 15:00:53 paladin: unsupport event "../configs/.application.toml.swp": REMOVE ingored
2019/11/21 15:00:53 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:00:53 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:00:53 paladin: unsupport event "../configs/.application.toml.swp": CHMOD ingored
2019/11/21 15:00:57 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:01:09 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:01:12 paladin: unsupport event "../configs/4913": REMOVE ingored
2019/11/21 15:01:12 paladin: unsupport event "../configs/application.toml": RENAME ingored
2019/11/21 15:01:12 paladin: load file: ../configs/application.toml~ error: open ../configs/application.toml~: no such file or directory, skipped
2019/11/21 15:01:12 paladin: reload config: application.toml events: 1
2019/11/21 15:01:12 paladin: reload config: application.toml events: 1
2019/11/21 15:01:12 paladin: unsupport event "../configs/application.toml": CHMOD ingored
2019/11/21 15:01:12 paladin: unsupport event "../configs/application.toml~": REMOVE ingored
2019/11/21 15:01:12 paladin: unsupport event "../configs/.application.toml.swp": REMOVE ingored
2019/11/21 15:05:19 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:05:19 paladin: unsupport event "../configs/.application.toml.swx": REMOVE ingored
2019/11/21 15:05:19 paladin: unsupport event "../configs/.application.toml.swp": REMOVE ingored
2019/11/21 15:05:19 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:05:19 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:05:19 paladin: unsupport event "../configs/.application.toml.swp": CHMOD ingored
2019/11/21 15:05:23 paladin: reload config: .application.toml.swp events: 0
2019/11/21 15:05:26 paladin: load file: ../configs/4913 error: open ../configs/4913: no such file or directory, skipped
2019/11/21 15:05:26 paladin: unsupport event "../configs/4913": REMOVE ingored
2019/11/21 15:05:26 paladin: unsupport event "../configs/application.toml": RENAME ingored
2019/11/21 15:05:26 paladin: reload config: application.toml events: 1
2019/11/21 15:05:26 paladin: reload config: application.toml events: 1
2019/11/21 15:05:26 paladin: unsupport event "../configs/application.toml": CHMOD ingored
2019/11/21 15:05:26 paladin: unsupport event "../configs/application.toml~": REMOVE ingored
2019/11/21 15:05:26 paladin: unsupport event "../configs/.application.toml.swp": REMOVE ingored

**Comment by Terry-Mao** [comment]
#438

**Comment by tomwei7** [comment]
fix on #438

**Comment by ryanwx** [comment]
windows 下依然有这个问题
