### ISSUE TITLE
文档中有错误

### ISSUE THREAD

**Issue by sanrentai** [bilibili/kratos#435]
按文档生成kratos-demo项目后，启动成功。需要在浏览器中打开 http://localhost:8000/abc/start才行

**Comment by zhangjinling** [comment]
你新建项目的名称 是 abc  ，所以路由就是abc，和新建项目的名称有关系，文档没有错误。

**Comment by ctrysbita** [comment]
0.3.1 的名称确实存在问题，不过master分支已经修复了。
可以请Maintainer尽快更新一下。

**Comment by Terry-Mao** [comment]
试下最新master
