### ISSUE TITLE
go1.13.4 can not install github.com/bilibili/kratos/tool/kratos 

### ISSUE THREAD

**Issue by zhangjinling** [bilibili/kratos#436]
go version：go version go1.13.4 windows/amd64
when install kratos： go get -u github.com/bilibili/kratos/tool/kratos
errors：

F:\code\src\github.com\bilibili\kratos\tool\kratos\build.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
F:\code\src\github.com\bilibili\kratos\tool\kratos\main.go:15:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
F:\code\src\github.com\bilibili\kratos\tool\kratos\main.go:64:45: cannot use ctx.Args() (type cli.Args) as type []string in argument to installAndRun
F:\code\src\github.com\bilibili\kratos\tool\kratos\run.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
F:\code\src\github.com\bilibili\kratos\tool\kratos\tool.go:74:41: cannot slice c.Args() (type cli.Args)

**Comment by skylz** [comment]
Mac  catalina ,go1.13.4 ,同样的错误

**Comment by lixuxian** [comment]
go version go1.13 darwin/amd64
../go/src/github.com/bilibili/kratos/tool/kratos/build.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
../go/src/github.com/bilibili/kratos/tool/kratos/main.go:15:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
../go/src/github.com/bilibili/kratos/tool/kratos/main.go:64:45: cannot use ctx.Args() (type cli.Args) as type []string in argument to installAndRun
../go/src/github.com/bilibili/kratos/tool/kratos/run.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
../go/src/github.com/bilibili/kratos/tool/kratos/tool.go:74:41: cannot slice c.Args() (type cli.Args)

**Comment by lixuxian** [comment]
me too

**Comment by ctrysbita** [comment]
See #426

**Comment by lixuxian** [comment]
thanks!

**Comment by lixuxian** [comment]
> See #426

thanks!
