### ISSUE TITLE
../api/client.go:15:68: undefined: DemoClient

### ISSUE THREAD

**Issue by skylz** [bilibili/kratos#439]
go version:1.13.4

go env:

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/skymac/Library/Caches/go-build"
GOENV="/Users/skymac/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/skymac/sky_work/go_work"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/skymac/sky_work/go_work/src/kratos-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6w/7vfbqgyj2klckr8kyzqfj40c0000gn/T/go-build759567413=/tmp/go-build -gno-record-gcc-switches -fno-common"

go build 报错
../api/client.go:15:68: undefined: DemoClient
../api/client.go:21:9: undefined: NewDemoClient

go get 获取的是v0.3.1，请问怎么获取master(Go 新手，请多指教)

**Comment by tonyboxes** [comment]
生成项目的日志可以发下看看，看着像是没生成pb，应该先安装下protobuf

**Comment by skylz** [comment]
安上protobuf 好了，3q
