### ISSUE TITLE
编译后没生成cmd

### ISSUE THREAD

**Issue by godsoul** [bilibili/kratos#44]
![image](https://user-images.githubusercontent.com/3104500/56806652-209f3f80-685f-11e9-99e0-3b6a2b12b38b.png)
编译后没生成cmd 也没报错

**Comment by tonyboxes** [comment]
module requires Go 1.12

go env看看环境？

**Comment by godsoul** [comment]
$ go env
GOARCH="amd64"
GOBIN="/Users/godsoul/soft/go/bin"
GOCACHE="/Users/godsoul/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/godsoul/code/go"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/Users/godsoul/soft/go"
GOTMPDIR=""
GOTOOLDIR="/Users/godsoul/soft/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/godsoul/code/go/bili/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p7/cm1dsc493lndjjw3tg1mk60h0000gn/T/go-build548164304=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by godsoul** [comment]
因为用go moudle，项目没有放在gopath下，有关系么？

**Comment by tonyboxes** [comment]
没关系的，go mod本来是放在gopath外面，你用的go 1.12吗？

**Comment by godsoul** [comment]
用的go 1.11 但是我mod文件里也改成1.11了

**Comment by tonyboxes** [comment]
额，控制台提示不能低于依赖的版本

**Comment by godsoul** [comment]
就是说必须用1.12编译吗？我mod文件里也改成1.11了啊

**Comment by tonyboxes** [comment]
嗯，因为依赖的库已经指定了 1.12，只是当前项目改应该不生效的

**Comment by lintanghui** [comment]
go version
cat go.mod
go build
依次执行这三个然后把输出信息贴出来看下

**Comment by tonyboxes** [comment]
@godsoul 更新到go 1.12可以了没的？

**Comment by lintanghui** [comment]
@godsoul  如果你要用1.11的话修改项目下go.mod 的同时还需要把kratos/go.mod 的版本改为1.11

**Comment by whtiehack** [comment]
检查下 %GOPATH/bin 目录

**Comment by godsoul** [comment]
换了版本好了，感谢
