### ISSUE TITLE
配置GOBIN可能会导致kratos工具不可用

### ISSUE THREAD

**Issue by wjl327** [bilibili/kratos#440]
如果系统配置了GOBIN环境变量，例如go env -w GOBIN=$HOME/bin。
此时运行 go get -u github.com/bilibili/kratos/tool/kratos 。二进制会安装在$HOME/bin目录下。
如果$HOME/bin不是$GOPATH/bin的话，执行会直接报错。

一、
如果$GOPATH没有bin目录则：
运行 genproject 出错: chdir $GOPATH/bin: no such file or directory
二、
如果$GOPATH有bin目录则：
运行 genproject 出错: fork/exec $GOPATH/bin/kratos-gen-project: no such file or directory

**Comment by Terry-Mao** [comment]
可以贡献一个pr，兼容GOBIN吗

**Comment by gatspy** [comment]
我也遇到这个问题. 没搞明白要怎么修改GOPATH?
`运行 genproject 出错: fork/exec $GOPATH/bin/kratos-gen-project: no such file or directory`

**Comment by laojianzi** [comment]
这些问题我在以下场景重现: 

 - 没有在任何环境变量文件中设置 `GOBIN` 和 `$GOPATH`
 - 使用 `go env -w GOBIN="$HOME/bin"` 的 go env 方式设置 `GOBIN`
 - 使用 `go env -w GOPATH=""` 的 go env 方式设置 `GOPATH`

当运行 `$HOME/bin/kratos-gen-project project_name` 时，`go get` 的 exec 就会出现 `运行 xxx 出错: chdir $GOPATH/bin: no such file or directory` 以及 `运行 xxx 出错: fork/exec $GOPATH/bin/xxx: no such file or directory` 的错误提示

---

尝试解决:

- 载入 [go env config](https://go.googlesource.com/proposal/+/master/design/30411-env.md) 到运行时 ENV
- 当 kratos 不能正确读取到 go env 的核心 ENV 设置时，引导用户正确设置

尝试载入 go env config

``` go
func gobin() string {
	if bin := os.Getenv("GOBIN"); len(bin) > 0 {
		return bin
	}

	// go env -w GOBIN="/go/bin"
	// e.g: ~/.config/go/env
	if configDir, err := os.UserConfigDir(); err == nil && len(configDir) > 0 &&
		godotenv.Load(filepath.Join(configDir, "go", "env")) == nil {
		if bin := os.Getenv("GOBIN"); len(bin) > 0 {
			return bin
		}
	}

	return filepath.Join(gopath(), "bin")
}
```

修改后可解决使用 `go env` 设置 `GOBIN` 导致 `kratos` 无法读取 `GOBIN` 问题.

ps: 目前只在 docker golang:1.13 中编译测试过

**Comment by zzg16** [comment]
我的解决办法如下，目前是可以创建成功了
`
GO111MODULE=on && go get -u github.com/bilibili/kratos/tool/kratos
`
`cd $GOPATH/src`
再执行如下命令
`
cd github.com/bilibili/kratos/tool/kratos-gen-project
`
`
go build 
`
`
go install 
`
而且要在环境变量里加上'GOBIN=$GOPATH/bin‘

**Comment by XyuWang** [comment]
已支持自定义gobin
