### ISSUE TITLE
创建的kratos-demo的api文件夹下文件缺失

### ISSUE THREAD

**Issue by kqbi** [bilibili/kratos#442]
kratos new kratos-demo -o kratos-demo -d D:\Go_WorkSpace\src --proto
go get -u github.com/bilibili/kratos/tool/kratos-protoc
protoc: 安装成功!
2019/11/28 15:45:50 protoc --proto_path=D:\Go_WorkSpace/src --proto_path=D:\Go_WorkSpace/src/github.com/bilibili/kratos/third_party --proto_path=D:\Go_Wor
kSpace\src\github.com\bilibili\kratos --bm_out=:. kratos-demo/api/api.proto
--bm_out: protoc-gen-bm: Plugin output is unparseable: Active code page: 65001\r\nz\264\016\n\031kratos-demo/api/api.bm.goz\226\016// Code generated by pr
otoc-gen-bm v0.1, DO NOT EDIT.\n// source: kratos-demo/api/api.proto\n\n/*\nPackage api is a generated blademaster stub package.\nThis code was generated
with kratos/tool/protobuf/protoc-gen-bm v0.1.\n\npackage \345\221\275\345\220\215\344\275\277\347\224\250 {appid}.{version} \347\232\204\346\226\271\345\2
74\217, version \345\275\242\345\246\202 v1, v2 ..\n\nIt is generated from these files:\n\tkratos-demo/api/api.proto\n*/\npackage api\n\nimport (\n\t\"context\"\n\n\tbm \"github.com/bilibili/kratos/pkg/net/http/blademaster\"\n\t\"github.
com/bilibili/kratos/pkg/net/http/blademaster/binding\"\n)\nimport google_protobuf1 \"github.com/golang/protobuf/ptypes/empty\"\n\n// to suppressed \'imported but not used warning\'\nvar _ *bm.Context\nvar _ context.Context\nvar _ binding
.StructValidator\n\nvar PathDemoSayHello = \"/demo.service.v1.Demo/SayHello\"\nvar PathDemoSayHelloURL = \"/kratos-demo/say_hello\"\n\n// DemoBMServer is the server API for Demo service.\ntype DemoBMServer interface {\n\tSayHello(ctx con
text.Context, req *HelloReq) (resp *google_protobuf1.Empty, err error)\n\n\tSayHelloURL(ctx context.Context, req *HelloReq) (resp *HelloResp, err error)\n}\n\nvar DemoSvc DemoBMServer\n\nfunc demoSayHello(c *bm.Context) {\n\tp := new(Hel
loReq)\n\tif err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get(\"Content-Type\"))); err != nil {\n\t\treturn\n\t}\n\tresp, err := DemoSvc.SayHello(c, p)\n\tc.JSON(resp, err)\n}\n\nfunc demoSayHelloURL(c *bm.Cont
ext) {\n\tp := new(HelloReq)\n\tif err := c.BindWith(p, binding.Default(c.Request.Method, c.Request.Header.Get(\"Content-Type\"))); err != nil {\n\t\treturn\n\t}\n\tresp, err := DemoSvc.SayHelloURL(c, p)\n\tc.JSON(resp, err)\n}\n\n// Reg
isterDemoBMServer Register the blademaster route\nfunc RegisterDemoBMServer(e *bm.Engine, server DemoBMServer) {\n\tDemoSvc = server\n\te.GET(\"/demo.service.v1.Demo/SayHello\", demoSayHello)\n\te.GET(\"/kratos-demo/say_hello\", demoSayH
elloURL)\n}\n
exit status 1
Project: kratos-demo
Owner: kratos-demo
Module Name: kratos-demo
WithGRPC: true
Directory: D:\Go_WorkSpace\src/kratos-demo

The application has been created.
这样生成的demo的api文件夹中只有api.proto和generate.go，文件不全

**Comment by kqbi** [comment]
用的kratos的master分支

**Comment by Sunknight945** [comment]
你好啊, 你这个 protoc-gen-bm: Plugin output is unparseable: Active code page: 65001 插件错误与我一样,
所以我想 请问 你在后来使用kratos_master之外 有没有用 protoc_gen_go 直接生成 go的文件, 最后(unparseable: Active code page: 65001)
这个错误怎么解决的?  如果有的话告诉我一下 谢谢..
