### ISSUE TITLE
问个初级问题-网关

### ISSUE THREAD

**Issue by namelcx** [bilibili/kratos#443]
没看到kratos的网关和相关文档呢

**Comment by Terry-Mao** [comment]
net/http/blademaster 里，具体什么问题呢？

**Comment by Terry-Mao** [comment]
https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/blademaster.md

**Comment by namelcx** [comment]
主要是之前看你的文章B站按业务有多个网关，但是像springcloud dubbo家族都是单一网关，这样的多网关真的好吗，怎么做统一的限流，监控，认证和鉴权？特别是鉴权那里。
不知道我理解的对不对
