### ISSUE TITLE
实在是理解不了dao模块怎么用？希望大神解释一下

### ISSUE THREAD

**Issue by QuanjieDeng** [bilibili/kratos#447]
dao层里面都是封装了一个数据层面的东西，数据库、缓存什么的，然后在构建的时候一层层传递
比如： redis->dao->service->http 
![image](https://user-images.githubusercontent.com/20788753/70211451-112a9200-1770-11ea-97a3-344c6380c74e.png)
我开始理解这种做法是吧一些基础组件整合一起，然后具体的server要使用，直接传递即可，但是我搞不明白的是，Service 
`type Service struct {
	ac  *paladin.Map
	dao dao.Dao
}`
里面把变量全都定义成小写，这让真正的service，比如http中，当我在实现一些逻辑的时候要使用redis的时候怎么获取到redis对象呢？
另外：
`type Dao interface {
	Close()
	Ping(ctx context.Context) (err error)
	// bts: -nullcache=&model.Article{ID:-1} -check_null_code=$!=nil&&$.ID==-1
	Article(c context.Context, id int64) (*model.Article, error)
}

// dao dao.
type dao struct {
	db          *sql.DB
	redis       *redis.Redis
	mc          *memcache.Memcache
	cache *fanout.Fanout
	demoExpire int32
}`
Dao模块是定义了interface,真正实现的是type dao struct，这样话在
type Service struct的方法中根本就拿不到 type  dao struct中的变量

**Comment by Terry-Mao** [comment]
我什么要去获取redis对象？
你访问Dao暴露的方法即可
