### ISSUE TITLE
kratos-demo cmd/main.go:21:23: undefined: di.InitApp

### ISSUE THREAD

**Issue by yiliaofan** [bilibili/kratos#451]
#  ~/work/golang/projects/src/kratos-demo  go build cmd/main.go
   command-line-arguments
cmd/main.go:21:23: undefined: di.InitApp
编译问题如何解决？ 谢谢！

# go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/fan/Library/Caches/go-build"
GOENV="/Users/fan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/fan/work/golang/projects"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/fan/work/golang/projects/src/kratos-demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/10/vk3b10z519ggknp_31qnhfb40000gn/T/go-build943985665=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by yinxiaodong** [comment]
刚刚也遇到了

GO111MODULE=on && go get -u github.com/bilibili/kratos/tool/kratos@master

master分支已经修复了这个问题

https://github.com/bilibili/kratos/issues/448#issuecomment-562409842

**Comment by firelph** [comment]
如何解决的呢

**Comment by 470054086** [comment]
同问 如果解决这个问题呢

**Comment by 470054086** [comment]
> 如何解决的呢

wire 是个第三方库 需要执行方法生成代码,在di目录下执行  kratos.exe t wire  生成代码  再次编译 执行就可以了
具体介绍 可以查看 https://blog.csdn.net/darjun/article/details/104623384
