### ISSUE TITLE
create new demo

### ISSUE THREAD

**Issue by Sakurasan** [bilibili/kratos#454]
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\hy\AppData\Local\go-build
set GOENV=C:\Users\hy\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\CODE\Go\GoPath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=E:\CODE\Go\GoPath\src\go.mod
set CGO_CFLAGS=-IC:\instantclient_11_2\sdk\include
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-LC:\instantclient_11_2\sdk\lib\msvc -loci
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\hy\AppData\Local\Temp\go-build346338354=/tmp/go-build -gno-record-gcc-switches

---

$ kratos new kratos-demo/
go get -u github.com/bilibili/kratos/tool/kratos-gen-project
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest
genproject: 安装成功!
can't load package: package onedemo/kratos-demo/cmd:
cmd\main.go:10:14: unknown escape sequence
cmd\main.go:10:19: unknown escape sequence
cmd\main.go:10:22: unknown escape sequence
cmd\main.go:10:29: unknown escape sequence
can't load package: package onedemo/kratos-demo/internal/dao:
internal\dao\dao.go:7:14: unknown escape sequence
internal\dao\dao.go:7:19: unknown escape sequence
internal\dao\dao.go:7:22: unknown escape sequence
internal\dao\dao.go:7:29: unknown escape sequence
can't load package: package onedemo/kratos-demo/internal/di:
internal\di\app.go:7:14: unknown escape sequence
internal\di\app.go:7:19: unknown escape sequence
internal\di\app.go:7:22: unknown escape sequence
internal\di\app.go:7:29: unknown escape sequence
can't load package: package onedemo/kratos-demo/internal/server/grpc:
internal\server\grpc\server.go:4:17: unknown escape sequence
internal\server\grpc\server.go:4:22: unknown escape sequence
internal\server\grpc\server.go:4:25: unknown escape sequence
internal\server\grpc\server.go:4:32: unknown escape sequence
can't load package: package onedemo/kratos-demo/internal/server/http:
internal\server\http\server.go:6:17: unknown escape sequence
internal\server\http\server.go:6:22: unknown escape sequence
internal\server\http\server.go:6:25: unknown escape sequence
internal\server\http\server.go:6:32: unknown escape sequence
internal\server\http\server.go:7:14: unknown escape sequence
internal\server\http\server.go:7:19: unknown escape sequence
internal\server\http\server.go:7:22: unknown escape sequence
internal\server\http\server.go:7:29: unknown escape sequence
can't load package: package onedemo/kratos-demo/internal/service:
internal\service\service.go:7:17: unknown escape sequence
internal\service\service.go:7:22: unknown escape sequence
internal\service\service.go:7:25: unknown escape sequence
internal\service\service.go:7:32: unknown escape sequence
internal\service\service.go:8:14: unknown escape sequence
internal\service\service.go:8:19: unknown escape sequence
internal\service\service.go:8:22: unknown escape sequence
internal\service\service.go:8:29: unknown escape sequence
go get -u github.com/bilibili/kratos/tool/kratos-protoc
protoc: 安装成功!
2019/12/12 16:56:46 protoc --proto_path=E:\CODE\Go\GoPath/src --proto_path=E:\CODE\Go\GoPath/pkg/mod/github.com/bilibili/kratos@v0.3.2-0.20191127025250-43a13f6aae20/third_party --proto_path=E:\CODE\Go\GoPath\src\kratos-demo\api --bm_out=:. api.proto
google/protobuf/descriptor.proto: File not found.
github.com/gogo/protobuf/gogoproto/gogo.proto:32:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
github.com/gogo/protobuf/gogoproto/gogo.proto:37:8: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto:44:8: "google.protobuf.EnumValueOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto:48:8: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FileOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto:82:8: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.MessageOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto:112:8: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.FieldOptions" is not defined.
google/protobuf/empty.proto: File not found.
google/api/annotations.proto:20:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
google/api/annotations.proto:28:8: "google.protobuf.MethodOptions" is not defined.
api.proto:6:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
api.proto:7:1: Import "google/protobuf/empty.proto" was not found or had errors.
api.proto:8:1: Import "google/api/annotations.proto" was not found or had errors.
api.proto:19:15: ".google.protobuf.Empty" is not defined.
api.proto:19:48: ".google.protobuf.Empty" is not defined.
api.proto:20:42: ".google.protobuf.Empty" is not defined.
exit status 1
exit status 1
exit status 1
exit status 1

$ export GO111MODULE=on && go get -u github.com/bilibili/kratos/tool/kratos
go: finding golang.org/x/sys latest

**Comment by tonyboxes** [comment]
这个是本地没安装好protobuf，或者是bin/protoc没有了include的对应文件，需要完整安装protobuf就可以了

**Comment by Randy618** [comment]
@tonyboxes 怎么完整安装protobuf,麻烦指教下，谢谢
