### ISSUE TITLE
quick start能够启动，但是报404Not found

### ISSUE THREAD

**Issue by newday1** [bilibili/kratos#455]
按照doc正常执行，日志如下，页面报错404，像是路由没有生效，新手不知道原因，求教

INFO 12/14-22:56:38.744 /home/kkdb/go/src/kratos-demo/cmd/main.go:19 abc start
2019/12/14 22:56:38 start watch filepath: ../configs
INFO 12/14-22:56:38.745 /home/kkdb/go/pkg/mod/github.com/bilibili/kratos@v0.3.2-0.20191127025250-43a13f6aae20/pkg/net/http/blademaster/server.go:98 blademaster: start http listen addr: 0.0.0.0:8000
[warden] config is Deprecated, argument will be ignored. please use -grpc flag or GRPC env to configure warden server.
INFO 12/14-22:56:38.745 /home/kkdb/go/pkg/mod/github.com/bilibili/kratos@v0.3.2-0.20191127025250-43a13f6aae20/pkg/net/rpc/warden/server.go:329 warden: start grpc listen addr: [::]:9000
INFO 12/14-22:56:50.328 http-access-log path=/kratos-demo/start stack=<nil> ip=[ msg=0 ts=1.8502e-05 timeout_quota=0.999942995 params= ret=0 err= method=GET user=no_user traceid= 
INFO 12/14-22:56:53.152 http-access-log msg=0 ts=8.757e-06 ret=0 stack=<nil> err= timeout_quota=0.999984608 method=GET ip=[ user=no_user path=/kratos-demo/start params= traceid= 
INFO 12/14-22:57:21.994 http-access-log user=no_user err= ts=8.957e-06 traceid= method=GET ip=[ path=/kratos-demo/start ret=0 stack=<nil> params= msg=0 timeout_quota=0.99997841

**Comment by tonyboxes** [comment]
@newday1 这个版本生成的path有点问题，需要自己修改internal/http/server.go为自己的path才可以
