### ISSUE TITLE
kratos install

### ISSUE THREAD

**Issue by JackShao** [bilibili/kratos#459]
使用go get -u github.com/bilibili/kratos/tool/kratos安装时出错，我的go版本是go1.13.3，系统是macOS 10.14.6。出错信息如下：
# github.com/bilibili/kratos/tool/kratos
go/src/github.com/bilibili/kratos/tool/kratos/build.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
go/src/github.com/bilibili/kratos/tool/kratos/main.go:15:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
go/src/github.com/bilibili/kratos/tool/kratos/main.go:64:45: cannot use ctx.Args() (type cli.Args) as type []string in argument to installAndRun
go/src/github.com/bilibili/kratos/tool/kratos/run.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
go/src/github.com/bilibili/kratos/tool/kratos/tool.go:74:41: cannot slice c.Args() (type cli.Args)

**Comment by shenzhigang** [comment]
请问你是怎么解决的？我也遇到同样的问题。
