### ISSUE TITLE
undefined: api.HelloReq

### ISSUE THREAD

**Issue by nabestv** [bilibili/kratos#46]
While installing and selecting the gPRC YES, I get this error:
```
# kratos-demo/internal/service
../internal/service/service.go:34:54: undefined: api.HelloReq
```

using this command:
```
cd kratos-demo/cmd <- this works
go build <- this is what throws the error
./cmd -conf ../configs <- not sure yet
```

If I select NO I have no issues and everything works... if I select the first build option, there are no issues.

I did have to convert Chinese into English, so some things may have translated incorrectly, but I think the terminal commands are pretty straight forward.

**Comment by lintanghui** [comment]
this had been mentioned at #41 . if you want to use grpc,  kprotoc must be installed to generate api.pb.go. you can use kratos/tool/kprotoc/install_kprotoc.sh to install this tool

**Comment by zhaoshichen1** [comment]
yes.

or you could run directly kratos/tool/kprotoc/kprotoc.sh to install protoc and then run this command:
protoc -I. --gogofast_out=plugins=grpc:. api.proto 
in this kratos-demo/api directory, thus you will get the api.pb.go file generated which could allow you build this project

**Comment by felixhao** [comment]
GOOS
* macos: shoult always be successful, if not install `protoc` and `gogo protobuf`, then run:
  *  `cd kratos-demo/api`
  *  `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`
* windows: install `protoc` and `gogo protobuf`，then run:
  *  `cd kratos-demo/api`
  *  `protoc --gogofast_out=plugins=grpc:$GOPATH/src api.proto`
  * `cd kratos-demo/cmd & go build`
* linux: install `protoc` first, then run:
  * `cd kratos-demo/api`
  * `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`
