### ISSUE TITLE
About ‘Audience Retention curve’ also named ‘高能进度条’

### ISSUE THREAD

**Issue by MickMo** [bilibili/kratos#460]
To be more github style，please allow me to use English。
I am very interesting in how bilibili implement “高能进度条”，Youtube and a indescribable site `P` have the same curve,which was named `Audience Retention curve`，but none of them release the detail about how they achieve this function.
so I wondering will you lovely guys release some detail info on this function?like how to collect data,where does it store,and data structure you guys use. etc.
I am pretty sure you guys will earn a lot reputation by doing so on github or anywhere else.

**Comment by mrytsr** [comment]
Hello, I am the creator of "高能进度条".It is also called
PBP(Progress Bar Plus) in our development procedure.
It's based on 3 elements:
1. User's seekend behavior.
2. Barrage density.
3. Spetial barrage works like "前方高能", "空降成功", etc.
PBP aims to improve user experience.
