### ISSUE TITLE
下载依赖包发生错误

### ISSUE THREAD

**Issue by pozxnm123** [bilibili/kratos#461]
go: finding github.com/shirou/gopsutil v2.19.6+incompatible
go list -m: github.com/shirou/gopsutil@v2.19.6+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

使用后发生错误
go版本是1.13

**Comment by luorou** [comment]
同样的问题...

**Comment by liangjisheng** [comment]
同样的问题

**Comment by xluer** [comment]
不支持1.13，go换1.12就好了

**Comment by liangjisheng** [comment]
不是go的版本的问题，好像是这个包的问题 github.com/shirou/gopsutil v2.19.6 换成v2.19.11就可以了

**Comment by Terry-Mao** [comment]
@liangjisheng 帮提个pr，修复下吧

**Comment by liangjisheng** [comment]
@Terry-Mao 好了

**Comment by liangjisheng** [comment]
continuous-integration/travis-ci/pr — The Travis CI build failed

**Comment by Terry-Mao** [comment]
#475
