### ISSUE TITLE
kratos包依赖错误

### ISSUE THREAD

**Issue by JohnSnooow** [bilibili/kratos#464]
cd discovery/cmd/discory
go build 报错
go: github.com/bilibili/kratos@v0.2.2 requires
	github.com/StackExchange/wmi@v0.0.0-20190523213609-cbe66965904d: invalid pseudo-version: does not match version-control timestamp (2019-05-23T21:33:15Z)

能升级下 kratos吗

**Comment by Terry-Mao** [comment]
master试试呢?

**Comment by Terry-Mao** [comment]
@JohnSnooow 你的问题解决了嘛

**Comment by JohnSnooow** [comment]
解决了，手动升级了下～
