### ISSUE TITLE
README里是不是有个错误？

### ISSUE THREAD

**Issue by shenzhigang** [bilibili/kratos#465]
> 打开浏览器访问：http://localhost:8000/kratos-demo/start，你会看到输出了Golang 大法好 ！！！
是不是得改成：
> 打开浏览器访问：http://localhost:8000/abc/start，你会看到输出了Golang 大法好 ！！！

**Comment by liangjisheng** [comment]
有这个错误
```go
func initRouter(e *bm.Engine) {
	e.Ping(ping)
	g := e.Group("/abc")
	{
		g.GET("/start", howToStart)
	}
}
```
@shenzhigang
