### ISSUE TITLE
master分支生成kratos失败！

### ISSUE THREAD

**Issue by namelcx** [bilibili/kratos#468]
按文档执行 GO111MODULE=on && go get -u github.com/bilibili/kratos/tool/kratos 出现一堆错误
都是跟github.com/urfave/cli相关

src/github.com/bilibili/kratos/tool/kratos/build.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
src/github.com/bilibili/kratos/tool/kratos/main.go:15:15: cannot use []cli.Command literal (type []cli.Command) as type []*cli.Command in assignment
src/github.com/bilibili/kratos/tool/kratos/main.go:64:45: cannot use ctx.Args() (type cli.Args) as type []string in argument to installAndRun
src/github.com/bilibili/kratos/tool/kratos/run.go:19:16: cannot use c.Args() (type cli.Args) as type []string in append
src/github.com/bilibili/kratos/tool/kratos/tool.go:74:41: cannot slice c.Args() (type cli.Args)

SOS

**Comment by shenzhigang** [comment]
试一下把两个命令分开执行，可能能解决你的问题。 
set GO111MODULE=on  （mac or linux上 export GO111MODULE=on)
go get -u github.com/bilibili/kratos/tool/kratos

**Comment by fzzf0618** [comment]
我也遇到这个问题了，有知道怎么解决的吗？go version 1.13.1
