### ISSUE TITLE
请问是每个微服务都要生成一套kratos-demo的目录吗？

### ISSUE THREAD

**Issue by zuiqiangqishao** [bilibili/kratos#469]
小白求解惑，kratos new project生成的项目目录是一个微服务的目录吧，一个项目会有很多个微服务，每个微服务下都需要这些目录吗，api、cmd、configs等。还有一个问题，是不是要在blademaster外面加一层网关啊，网关再转发请求到blademaster的http端口上，抱歉新手有点不懂，还请帮忙解答

**Comment by mfslog** [comment]
是这样的，没有理解错。

**Comment by zuiqiangqishao** [comment]
好的，谢谢
