### ISSUE TITLE
PS E:\GoProject\bin> .\kratos.exe tool install all kratos: 安装成功! ln: failed to create symbolic link 'E/bin/kprotoc': No such file or directory

### ISSUE THREAD

**Issue by xiaojia21190** [bilibili/kratos#47]

**Comment by felixhao** [comment]
GOOS
* macos: shoult always be successful, if not install `protoc` and `gogo protobuf`, then run:
  *  `cd kratos-demo/api`
  *  `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`
* windows: install `protoc` and `gogo protobuf`，then run:
  *  `cd kratos-demo/api`
  *  `protoc --gogofast_out=plugins=grpc:$GOPATH/src api.proto`
  * `cd kratos-demo/cmd & go build`
* linux: install `protoc` first, then run:
  * `cd kratos-demo/api`
  * `kratos tool kprotoc`
  * `cd kratos-demo/cmd & go build`

protoc:https://github.com/protocolbuffers/protobuf#protocol-compiler-installation
gogo protobuf:https://github.com/gogo/protobuf
kratos tool:https://github.com/bilibili/kratos/blob/master/doc/wiki-cn/kratos-tool.md

**Comment by xiaojia21190** [comment]
PS E:\GoProject\src\kratos-demo\api> protoc --gogofast_out=plugins=grpc:$GOPATH/src api.proto
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
api.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
问一下这个该怎么解决，所有包都下了

**Comment by xiaojia21190** [comment]
![image](https://user-images.githubusercontent.com/16084693/56859346-dc758180-69bb-11e9-9b63-9f14881c47e5.png)
这个bao包在pkg下面，这里执行的话，说找不到包
