### ISSUE TITLE
mac need brew pre-installed

### ISSUE THREAD

**Issue by byxiangfei** [bilibili/kratos#488]
$ kratos new kratos-demo
go: finding github.com/bilibili/kratos master
brew install protobuf
2020/01/09 22:54:03 exec: "brew": executable file not found in $PATH
exit status 1
Close: 无声明 忽略此方法
Ping: 无声明 忽略此方法
dao.bts.go: 生成成功
mc.cache.go: 生成成功
wire: /Users/ndong/go/workspace/kratos-demo/internal/di/wire.go:17:65: DemoServer not declared by package api
wire: generate failed
exit status 1
Project: kratos-demo
OnlyGRPC: false
OnlyHTTP: false

**Comment by healer111458** [comment]
<view>healer</view>





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by XyuWang** [comment]
可以安装一下brew 再重新执行试试
