### ISSUE TITLE
这有点尴尬。。。开了goproxy无法安装

### ISSUE THREAD

**Issue by 514366607** [bilibili/kratos#490]
go get -u github.com/bilibili/kratos/tool/kratos
go get: github.com/bilibili/kratos@v0.3.1 requires
        github.com/shirou/gopsutil@v2.19.6+incompatible: reading https://goproxy.io/github.com/shirou/gopsutil/@v/v2.19.6+incompatible.mod: 410 Gone

**Comment by 514366607** [comment]
https://goproxy.io/github.com/shirou/gopsutil/@v/v2.19.9+incompatible.mod

2.19.9以上才有文件。能不能改下本项目的mod?

**Comment by 514366607** [comment]
看到master已经改为11了，啥时候打个新tag？不然没法安装。

**Comment by Terry-Mao** [comment]
@514366607 已经打了新tag 试试？
