### ISSUE TITLE
怎么做单元测试？

### ISSUE THREAD

**Issue by greyireland** [bilibili/kratos#493]
主要有一些依赖：
- 数据库
- redis
- 三方调用
- 其他函数

如何解耦

**Comment by Terry-Mao** [comment]
testing/lich，以及我们关于UT的doc可以参考下，核心是基于Docker Compose来解决的

**Comment by Terry-Mao** [comment]
第三方依赖，一般多是gRPC（我们假设你已经统一），基于gRPC Client Interface来做Mock，其他函数应该是依赖抽象而非实现

**Comment by greyireland** [comment]
> testing/lich，以及我们关于UT的doc可以参考下，核心是基于Docker Compose来解决的

运行单元测试的环境是在容器之外吧，CICD的流程是如何进行？

**Comment by Terry-Mao** [comment]
运行单元测试是在Docker里，Dind Docker in Docker，我们内部是基于k8s prow 改造的CICD
