### ISSUE TITLE
go get -u github.com/bilibili/kratos/tool/kratos 异常

### ISSUE THREAD

**Issue by lvoooo** [bilibili/kratos#495]
![image](https://user-images.githubusercontent.com/16740247/72421055-c6faee80-37ba-11ea-9de1-5a1cf8573faf.png)

**Comment by tonyboxes** [comment]
我这边go1.13.x看着正常，本地的go version是那个版本的？

**Comment by wlkfec** [comment]
我这边软件版本是 go version go1.13.5 windows/amd64  也是出现这种错误，命令没有安装成功

**Comment by tonyboxes** [comment]
GO111MODULE=on && go get -u github.com/bilibili/kratos/tool/kratos

可以加个go mod为on试试

**Comment by wlkfec** [comment]
设置这个变量后  没有报错了  但是依然提示找不到kratos命令  是需要手动设置位置吗？

**Comment by ijijni** [comment]
我也出现了这个问题，win10环境。go version 1.13.5 .
![image](https://user-images.githubusercontent.com/16640527/72661402-6b2ba200-3a14-11ea-8137-bc3c6ffb41f0.png)

**Comment by Linij** [comment]
macOS 10.15.3 Beta版(19D62e)
![image](https://user-images.githubusercontent.com/8857514/72693807-79410600-3b6d-11ea-8b87-1260d4edc378.png)

**Comment by XyuWang** [comment]
请升级到v0.3.3
