### ISSUE TITLE
Windows上，执行测试错误: No such service: db 

### ISSUE THREAD

**Issue by Ioridy** [bilibili/kratos#496]
在Windows上运行kratos-demo的测试，发现提示（No such service: db ），debug跟进后发现，程序中拼装daocker 命令时，使用上一条命令的输出做字符串分割，但是里面包含**空白字节**，导致程序中docker命令一直执行失败。
同时在macOS做了验证，输出是中间是没有**空白字符的**，提个issue，不知道是我环境特殊，还是Windows上都有这个问题。
![output](https://user-images.githubusercontent.com/6879800/72673698-3fa6c700-3aa9-11ea-82bd-a48aae53894d.jpg)

**Comment by otokaze** [comment]
已经安排上了！https://github.com/bilibili/kratos/pull/499
顺带安利一波我们的ut代码自动生成工具：github.com/bilibili/kratos/tool/testgen

期待老哥的再次反馈~

**Comment by Ioridy** [comment]
打算项目用，一直在验证熟悉，年后正式开工，话说关于你们应用的CI流程有没有相关资料推荐下（或者给个思路，方向）。

**Comment by otokaze** [comment]
> 打算项目用，一直在验证熟悉，年后正式开工，话说关于你们应用的CI流程有没有相关资料推荐下（或者给个思路，方向）。

CI这个你们完全可以按照自己的想法用现有的工具去实现，Gitlab本身就自带Pipeline的CI，当然也有像Drone这些开源又轻量的解决方案，包括Github现在都已经开放action了，都是可行的解决方案。

**Comment by Terry-Mao** [comment]
@Ioridy 试试这个PR可以解决你的问题吗？
