### ISSUE TITLE
关于负载均衡

### ISSUE THREAD

**Issue by Yukibana** [bilibili/kratos#503]
想问一下如果使用kratos和discovery搭建微服务的话，接口/聚合层的微服务应该怎么做http的负载均衡呢？spring-cloud生态里面可以用zuul和eureka实现动态负载均衡，kratos有没有类似的组件可以实现这样的效果呢~

**Comment by Terry-Mao** [comment]
BFF之上一般是API Gateway，可以使用Envoy/Ingress/OR/Kong
