### ISSUE TITLE
现在的Kratos，可以用于生产环境开发吗？

### ISSUE THREAD

**Issue by chenquan** [bilibili/kratos#510]
现在的Kratos，可以用于生产环境开发吗？最近有想要使用kratos编写一个web网站的想法，但是不知道现在它的稳定状况如何，想听听大家都意见。

**Comment by schickal** [comment]
没踩过坑不知道，其他几个流行库改过来的，估计问题不大。kratos tool还不太行，指令的路径很混乱，也不支持go module。拿来学习挺好的，建议直接用example改吧。

**Comment by chenquan** [comment]
> 没踩过坑不知道，其他几个流行库改过来的，估计问题不大。kratos tool还不太行，指令的路径很混乱，也不支持go module。拿来学习挺好的，建议直接用example改吧。

我放弃使用kratos了，怕坑太多。还是等它稳定之后再说吧。

**Comment by Terry-Mao** [comment]
B站在使用
