### ISSUE TITLE
问题找到了，以为proto3有一些新类型，这些新类型的proto文件找不到就会出错。首先下载proroc的源码： https://github.com/protocolbuffers/protobuf/releases。 然后这个文件夹下面又一个google的文件夹里面就是这些文件。可以将protoc的目录手动多添加一个，也可以将整个google文件夹拷贝到kratos命令的一个目录下，也就是GOPATH/src下面就 ok，浪费好久时间。

### ISSUE THREAD

**Issue by jialiming** [bilibili/kratos#516]
问题找到了，以为proto3有一些新类型，这些新类型的proto文件找不到就会出错。首先下载proroc的源码： https://github.com/protocolbuffers/protobuf/releases。 然后这个文件夹下面又一个google的文件夹里面就是这些文件。可以将protoc的目录手动多添加一个，也可以将整个google文件夹拷贝到kratos命令的一个目录下，也就是GOPATH/src下面就 ok，浪费好久时间。

_Originally posted by @luyingjie in https://github.com/bilibili/kratos/issues/514#issuecomment-596205916_

**Comment by jialiming** [comment]
问题解决了

**Comment by gosundy** [comment]
GO111MODULE=off go get github.com/gogo/protobuf/...  应该是检测$GOPATH/src的protobuf
