### ISSUE TITLE
API 设计: Options、Config 讨论

### ISSUE THREAD

**Issue by Terry-Mao** [bilibili/kratos#53]
目前Kratos中大量都是依赖Config来初始化的，这是为了适配配置文件解析和加载，但是Kratos可能作为vendor第三方库给其他人使用，那么就需要他们自己的初始化解析配置的方式，因此API最好是提供两种，一种是全套使用kratos tool 工具链 利用toml或者将来yaml方式来启动，一种是把kratos当做第三方库，自己初始化组件，那么使用options会比较方便

**Comment by tonyboxes** [comment]
其实框架里面应该多实现Value UnmarshalYAML就可以了，然后是kratos tool默认那种，参数选择？

**Comment by Terry-Mao** [comment]
@tonyboxes 针对tool可以作为参数来处理，pkg还需要处理初始化option问题
