### ISSUE TITLE
rate/limit: implement bbr-like limiter

### ISSUE THREAD

**Issue by Terry-Mao** [bilibili/kratos#59]
一、采样指标

a, cpu，最近 1s 的 CPU 均值，采样周期 250ms

cpu 使用一个独立的 goroutine 采样，每隔 250ms 触发一次（和 sys/stat 中的间隔保持一致）。在计算均值时，cpu 仅仅使用了简单滑动平均。

b, inflight，当前处理中的请求数量

c, pass，最近5s，每100ms内请求成功的数量

d, rt，最近5s，每100ms内请求的响应时间

e, prevDrop，最近一次丢弃请求的时间

二、限流算法
判断是否丢弃当前请求的算法如下：

cpu > 800 AND (Now - PrevDrop) < 1s AND (MaxPass * MinRt * windows / 1000) < InFlight

MaxPass 表示最近 5s 内，单个采样窗口中最大的请求数。

MinRt 表示最近 5s 内，单个采样窗口中最小的响应时间。

windows 表示一秒内采样窗口的数量，默认配置中是 5s 50 个采样，那么 windows 的值为 10。

三、其他事项

a,  保留了冷却时间，来判断当前是否超载

原因：

限流效果生效后，cpu 会在临界值（800）附近抖动，如果不使用冷却时间，那么一个短时间的 cpu 下降就可能导致大量请求被放行，严重时会打满 cpu

使用滑动平均无法解决 cpu 在高负载时下滑问题，即使使用平均，也会出现 cpu 下滑，cpu 打满的问题
![image](https://user-images.githubusercontent.com/1627804/56940568-ee812c80-6b41-11e9-88cc-932038aecf90.png)
b, 最小 rt 使用的是采样窗口的平均 rt（sentinal 使用的是最小点的 rt）

压测发现使用最小点的 rt 可能会造成限流过度，即窗口没有及时放大，导致较多流量被拒绝

c, 限流对部分场景无效

请求上升后，cpu 变化不大

非请求上升造成的 cpu 上升

**Comment by Terry-Mao** [comment]
!105

**Comment by Terry-Mao** [comment]
#105

**Comment by henrycjchen** [comment]
这里冷却时间做的是什么事情呢？
