### ISSUE TITLE
database-mysql.md文档什么时候会完善

### ISSUE THREAD

**Issue by VeblenXSYK** [bilibili/kratos#65]
使用kratos-demo与mysql连接，发现无论怎么更改mysql.toml中的内容，都没有效果，但是sql.NewMySQL(dc.Demo)也没有出现panic，所以想问问database-mysql.md文档什么时候会完善？

**Comment by gie777** [comment]
@VeblenXSYK   我是看的gorm的文档学的..... 	Conf    是看的toml 然后,解析配置文档,注册数据库,.就可以了,如果连不行你可以打印一个err

**Comment by VeblenXSYK** [comment]
> @VeblenXSYK 我是看的gorm的文档学的..... Conf 是看的toml 然后,解析配置文档,注册数据库,.就可以了,如果连不行你可以打印一个err
我单步调试通过sql.NewMySQL(dc.Demo)，没有出现数据库连接出错的信息，但是我在mysql.toml中的数据库配置是故意写错的，所以觉得很奇怪

**Comment by gie777** [comment]
> @gie777
> 我单步调试通过sql.NewMySQL(dc.Demo)，没有出现数据库连接出错的信息，但是我在mysql.toml中的数据库配置是故意写错的，所以觉得很奇怪

我没用他们写的基础库,我用的orm gorm自己拼的.....你可以看一下基础库你打一下断点,看是不是少判断错误语句了,而且你执行,ping 的时候才会调用mysql 你写model逻辑了么...

**Comment by VeblenXSYK** [comment]
@gie777 
明白了，是我的理解出了问题，我之前认为“只要kratos运行起来，且没有出现数据库连接错误，就说明数据库已经成功连接了，所以通过show processlist会查看到新的连接”，其实kratos只是在需要进行数据库操作的时候才真正的进行数据库的连接。另外决定数据库的正确连接与toml配置文件中的addr无关，所以错误的修改也不影响数据库的连接

**Comment by wujunze** [comment]
试一下 Ping 会连接数据库

**Comment by wujunze** [comment]
我现在遇到一个问题  toml配置 mysql连接的 ip 是127.0.0.2   报错信息里面一直是 172.19.0.1  
项目全局搜索这个 172.19.0.1  也没有发现  是什么原因 @Terry-Mao
