### ISSUE TITLE
quick-start里面kratos-demo拼写问题导致的404

### ISSUE THREAD

**Issue by stonezpl** [bilibili/kratos#66]
func initRouter(e *bm.Engine) {
	e.Ping(ping)
	g := e.Group("/karatos-demo")
	{
		g.GET("/start", howToStart)
	}
}
访问/kratos-demo/start一直是404，看了上面的代码，发现拼写错了

**Comment by tonyboxes** [comment]
是不是在kratos new时写错了的？

**Comment by gie777** [comment]
g := e.Group("/**karatos**-demo")
}
karatos karatos karatos
kratos kratos kratos
访问/kratos-demo/start
拼错了,多了一个a

**Comment by tonyboxes** [comment]
是自己创建项目时拼的项目名，还是怎么创建出来的呢？

**Comment by gie777** [comment]
> 是自己创建项目时拼的项目名，还是怎么创建出来的呢？这个是创建时自己填的项目名字。

是他自己建立项目的时候拼错了
