### ISSUE TITLE
demo里面不能生成API文件夹

### ISSUE THREAD

**Issue by liu-song** [bilibili/kratos#73]
mod 开启了 是1.12 版本

build kratos-demoha/cmd: cannot load kratos-demoha/api: cannot find module providing package kratos-demoha/api

**Comment by liu-song** [comment]
执行命令   kratos new kratos-demo   生成的demo 里面没有API 文件夹

**Comment by tonyboxes** [comment]
先加一下 --proto，这个等下修复
```kratos new kratos-demo --proto```

**Comment by xiaojia21190** [comment]
(base) ☁  kratos-demo  kratos tool protoc api.proto
go get -u github.com/bilibili/kratos/tool/krotos-protoc
go: finding github.com/bilibili/kratos/tool/krotos-protoc latest
go: finding github.com/bilibili/kratos/tool latest
go: finding github.com/bilibili/kratos latest
go get github.com/bilibili/kratos/tool/krotos-protoc: no matching versions for query "latest"
运行 protoc 出错: fork/exec /Users/jws/go/bin/kratos-protoc: no such file or directory

**Comment by starDemo** [comment]
@xiaojia21190  一个骚操作可以救急 
```bash
cd $GOPATH/src/github.com/bilibili/kratos/tool/kratos-protoc/
go build 
mv ./kratos-protoc $GOPATH/bin/
kratos tool install all
kratos-protoc
```
