### ISSUE TITLE
支持 cli 模式么？

### ISSUE THREAD

**Issue by jianhuihi** [bilibili/kratos#78]
RT

**Comment by tonyboxes** [comment]
没太明白？kratos工具链都是cli的

**Comment by jianhuihi** [comment]
想跑个cli脚本  

调用kratos的Service  不知道怎么下手了

**Comment by tonyboxes** [comment]
我们是通过grpc&http进行定义service api的，可以postman工具进行调用http，要是grpc估计需要个对应的测试工具

**Comment by jianhuihi** [comment]
1、期望能通过cli模式直接调用Service的方法
2、期望能通过cli模式调用grpc service api

**Comment by jianhuihi** [comment]
已经解决

**Comment by pinguo-fuzhiyong** [comment]
怎么解决的啊？
