### ISSUE TITLE
kratos new 代码生成错误

### ISSUE THREAD

**Issue by TangGaolin** [bilibili/kratos#86]
操作步骤：
go get -u github.com/bilibili/kratos/tool/kratos
kratos new kratos-demo
 文件 kratos-demo/cmd/main.go:
第35行多出一个 } 符号

![image](https://user-images.githubusercontent.com/10041852/57355356-6a155600-71a0-11e9-8f62-f58c5ac43131.png)

**Comment by felixhao** [comment]
#88

**Comment by keets2012** [comment]
execute `kratos new kratos-demo`
 > No help topic for 'new'

how to resolve?
